package org.Custom.Transformations.formats.gene.arquitectura;

import java.util.HashMap;

public class UtilitzacioType extends HashMap<Integer, String>{
    public UtilitzacioType() {
        this.put(1, "Abadia");
        this.put(2, "Abandonat");
        this.put(3, "Abeurador");
        this.put(4, "Acadèmia");
        this.put(5, "Accessoris d'edificis");
        this.put(6, "Agrícola");
        this.put(7, "Agrícola-Ramadera-Habitatge");
        this.put(8, "Aixada");
        this.put(9, "Aixeta");
        this.put(10, "Aixopluc");
        this.put(11, "Ajuntament");
        this.put(12, "Alberg");
        this.put(13, "Altar");
        this.put(14, "Altres");
        this.put(15, "Altres fortificacions");
        this.put(16, "Altres usos");
        this.put(17, "Altres usos militars");
        this.put(18, "Ambulatori");
        this.put(19, "Antipendi");
        this.put(20, "Ara");
        this.put(21, "Arada");
        this.put(22, "Arrambador");
        this.put(23, "Arxiu");
        this.put(24, "Asil-llar de vells");
        this.put(25, "Associació de veïns");
        this.put(26, "Associacions");
        this.put(27, "Ateneu");
        this.put(28, "Auditori");
        this.put(29, "Balcó");
        this.put(30, "Balneari");
        this.put(31, "Banc");
        this.put(32, "Bar");
        this.put(33, "Barraca");
        this.put(34, "Barraca de caçador");
        this.put(35, "Biblioteca");
        this.put(37, "Biga");
        this.put(38, "Borda");
        this.put(39, "Botiga");
        this.put(40, "Bústia");
        this.put(41, "Cabana");
        this.put(42, "Cabana de pastor");
        this.put(43, "Cabana de vinya");
        this.put(44, "Cafeteria");
        this.put(45, "Calçat");
        this.put(46, "Calaixera");
        this.put(47, "Calvari");
        this.put(48, "Calze");
        this.put(49, "Camí");
        this.put(50, "Cambra agrària");
        this.put(51, "Camp aviació");
        this.put(53, "Campana");
        this.put(54, "Campanar");
        this.put(55, "Canal");
        this.put(56, "Canònica");
        this.put(57, "Cap de biga");
        this.put(58, "Capella");
        this.put(59, "Capella lateral");
        this.put(60, "Capella-Canònica");
        this.put(61, "Capella-Cartoixa");
        this.put(62, "Capella-Castell");
        this.put(63, "Capella-Cementiri");
        this.put(64, "Capella-Col.legi");
        this.put(65, "Capella-Convent");
        this.put(66, "Capella-Escola");
        this.put(67, "Capella-Hospital");
        this.put(68, "Capella-Institució");
        this.put(69, "Capella-Masia");
        this.put(70, "Capella-Monestir");
        this.put(71, "Capella-Palau");
        this.put(72, "Capgròs");
        this.put(73, "Capitell");
        this.put(74, "Carrer");
        this.put(75, "Cartoixa");
        this.put(76, "Casa de colònies");
        this.put(77, "Casa de cultura");
        this.put(78, "Casa forta");
        this.put(79, "Casa senyorial");
        this.put(80, "Casal");
        this.put(81, "Casal de joves");
        this.put(82, "Casal de vells");
        this.put(83, "Casal fortificat");
        this.put(84, "Caserna");
        this.put(85, "Casino");
        this.put(86, "Castell");
        this.put(87, "Catedral");
        this.put(88, "Cava");
        this.put(89, "Cel.la");
        this.put(90, "Celler");
        this.put(92, "Celler cooperatiu");
        this.put(93, "Cementiri");
        this.put(94, "Central elèctrica");
        this.put(95, "Central tèrmica");
        this.put(96, "Centre cultural");
        this.put(97, "Centre excursionista");
        this.put(98, "Centre recreatiu");
        this.put(99, "Ceràmica");
        this.put(100, "Cinema");
        this.put(101, "Cisterna");
        this.put(102, "Ciutadella");
        this.put(103, "Clínica");
        this.put(104, "Clau de volta");
        this.put(105, "Claustre");
        this.put(106, "Cleda");
        this.put(107, "Club");
        this.put(108, "Col·legi professional");
        this.put(109, "Colònia industrial");
        this.put(110, "Colomar");
        this.put(111, "Columna");
        this.put(112, "Comercial");
        this.put(113, "Complement");
        this.put(114, "Comunidor");
        this.put(115, "Conducció d'aigua");
        this.put(116, "Consell Comarcal");
        this.put(117, "Construcció efímera");
        this.put(118, "Convent");
        this.put(119, "Cooperativa agrícola");
        this.put(120, "Corral");
        this.put(121, "Correus");
        this.put(122, "Cort");
        this.put(123, "Cortinatges");
        this.put(124, "Cotxeres");
        this.put(125, "Creu de terme");
        this.put(126, "Creu processional");
        this.put(127, "Cuina");
        this.put(129, "Culte");
        this.put(130, "Culte-habitatge");
        this.put(131, "Cultura");
        this.put(132, "Cups");
        this.put(133, "Custòdia");
        this.put(134, "Defensiva");
        this.put(135, "Defensiva-culte");
        this.put(136, "Defensiva-habitatge");
        this.put(137, "Dependències diverses");
        this.put(138, "Desaparegut");
        this.put(139, "Diputació");
        this.put(140, "Dispensari");
        this.put(141, "Dormitori");
        this.put(142, "Drassanes");
        this.put(143, "Editorial");
        this.put(144, "Egrafiats");
        this.put(145, "Eines agrícoles");
        this.put(146, "Empedrat");
        this.put(147, "En desús");
        this.put(148, "Enrajolat");
        this.put(149, "Ensenyament");
        this.put(150, "Ensenyament-habitatge");
        this.put(151, "Enteixinat");
        this.put(152, "Entitat bancària");
        this.put(153, "Equipaments industrials");
        this.put(154, "Ermita");
        this.put(155, "Escala");
        this.put(156, "Escola");
        this.put(157, "Escola d'arts i oficis");
        this.put(158, "Escola d'estiu");
        this.put(159, "Escola de música");
        this.put(160, "Escola taller");
        this.put(161, "Escorxador");
        this.put(162, "Escultura");
        this.put(163, "Església");
        this.put(164, "Església fortificada");
        this.put(165, "Església-Canònica");
        this.put(166, "Església-Cartoixa");
        this.put(167, "Església-Castell");
        this.put(168, "Església-Cementiri");
        this.put(169, "Església-Col.legi");
        this.put(170, "Església-Convent");
        this.put(171, "Església-Escola");
        this.put(172, "Església-Hospital");
        this.put(173, "Església-Institució");
        this.put(174, "Església-Masia");
        this.put(175, "Església-Monestir");
        this.put(176, "Església-Palau");
        this.put(177, "Espais de comunicació");
        this.put(178, "Espais de lleure");
        this.put(179, "Espais de lleure-comunicació");
        this.put(180, "Esplai");
        this.put(181, "Estable");
        this.put(182, "Estació");
        this.put(183, "Estela funerària");
        this.put(184, "Estructura o construcció");
        this.put(185, "Fàbrica");
        this.put(186, "Fanal");
        this.put(187, "Far");
        this.put(188, "Farga");
        this.put(190, "Fassina");
        this.put(191, "Filmoteca");
        this.put(192, "Finestra");
        this.put(193, "Fonda");
        this.put(194, "Fonoteca");
        this.put(195, "Font");
        this.put(196, "Forn");
        this.put(197, "Forn de calç");
        this.put(198, "Forn de pa");
        this.put(199, "Forrellat");
        this.put(200, "Fort");
        this.put(201, "Fortí");
        this.put(202, "Fortalesa");
        this.put(203, "Frontal d'altar");
        this.put(204, "Gàrgola");
        this.put(205, "Galeria d'art");
        this.put(206, "Garatge");
        this.put(207, "Gegant");
        this.put(208, "Generalitat");
        this.put(209, "Glorieta");
        this.put(210, "Govern civil");
        this.put(211, "Govern militar");
        this.put(212, "Graner");
        this.put(213, "Granja");
        this.put(214, "Gravat");
        this.put(215, "Guarderia");
        this.put(216, "Habitatge");
        this.put(217, "Habitatge d'obrers");
        this.put(218, "Habitatge de canonges");
        this.put(219, "Habitatge de monjos");
        this.put(220, "Habitatge plurifamiliar");
        this.put(221, "Habitatge temporer");
        this.put(222, "Habitatge unifamiliar");
        this.put(223, "Hemeroteca");
        this.put(224, "Hospici");
        this.put(225, "Hospital");
        this.put(226, "Hostal");
        this.put(227, "Hotel");
        this.put(228, "Imatge");
        this.put(229, "Indumentària");
        this.put(230, "Industrial");
        this.put(231, "Industrial-habitatge");
        this.put(232, "Instal.lació esportiva");
        this.put(233, "Instal.lació minera");
        this.put(234, "Institut");
        this.put(235, "Instrument musical");
        this.put(236, "Interiors");
        this.put(237, "Internat");
        this.put(238, "Jardí");
        this.put(239, "Joia");
        this.put(240, "Jutjat");
        this.put(241, "Llençols");
        this.put(242, "Lleure");
        this.put(243, "Llinda");
        this.put(244, "Llindar");
        this.put(245, "Llit");
        this.put(246, "Llosa sepulcral");
        this.put(247, "Llum");
        this.put(248, "Mènsula");
        this.put(249, "Magatzem");
        this.put(250, "Maquinària diversa");
        this.put(251, "Mas");
        this.put(252, "Masia");
        this.put(253, "Masia fortificada");
        this.put(254, "Masoveria");
        this.put(255, "Maternitat");
        this.put(256, "Mecanismes");
        this.put(257, "Mercat");
        this.put(258, "Militar");
        this.put(259, "Mina d'aigua");
        this.put(260, "Mirador");
        this.put(261, "Mobiliari");
        this.put(262, "Mobiliari urbà");
        this.put(263, "Molí");
        this.put(264, "Molí d'aigua");
        this.put(265, "Molí d'oli");
        this.put(266, "Molí draper");
        this.put(267, "Molí fariner");
        this.put(268, "Molí paperer");
        this.put(269, "Monestir");
        this.put(270, "Monument");
        this.put(271, "Monument commemoratiu");
        this.put(272, "Monument funerari");
        this.put(274, "Mosaic");
        this.put(275, "Muralla");
        this.put(276, "Museu");
        this.put(277, "Objectes d'art");
        this.put(278, "Objectes d'art popular");
        this.put(279, "Objectes de culte");
        this.put(280, "Obrador artesà");
        this.put(281, "Oficina");
        this.put(282, "Oratori");
        this.put(283, "Orfebreria");
        this.put(284, "Orfeó");
        this.put(285, "Palau");
        this.put(286, "Palau de l'abat");
        this.put(287, "Palau episcopal");
        this.put(288, "Pallissa");
        this.put(289, "Panteó");
        this.put(290, "Pany");
        this.put(291, "Parament de la llar");
        this.put(292, "Parc");
        this.put(293, "Paret");
        this.put(294, "Parròquia");
        this.put(295, "Part d'estructura o d'edifici");
        this.put(296, "Parvulari");
        this.put(297, "Passeig");
        this.put(298, "Paviment");
        this.put(299, "Pendent");
        this.put(300, "Pensió");
        this.put(301, "Pesquera");
        this.put(302, "Pesqueres");
        this.put(303, "Pica baptismal");
        this.put(304, "Pica beneitera");
        this.put(305, "Pintura");
        this.put(306, "Pintura mural");
        this.put(307, "Plaça");
        this.put(308, "Plafó ceràmic");
        this.put(309, "Pont");
        this.put(310, "Port");
        this.put(311, "Porta");
        this.put(312, "Portada");
        this.put(313, "Portal");
        this.put(314, "Pou");
        this.put(315, "Pou de gel");
        this.put(316, "Pre-industrial");
        this.put(317, "Presó");
        this.put(318, "Quadra");
        this.put(319, "Quadre");
        this.put(320, "Quiosc");
        this.put(321, "Ramadera");
        this.put(322, "Rasclet");
        this.put(323, "Rectoria");
        this.put(324, "Refetor");
        this.put(325, "Reformatori");
        this.put(326, "Refugi");
        this.put(327, "Refugi de muntanya");
        this.put(328, "Reixa");
        this.put(329, "Reliquiari");
        this.put(330, "Relleu");
        this.put(331, "Rellotge");
        this.put(332, "Rellotge de sol");
        this.put(333, "Resclosa");
        this.put(334, "Residència");
        this.put(335, "Residència comtal");
        this.put(336, "Residència d'estudiants");
        this.put(337, "Residència episcopal");
        this.put(338, "Residència reial");
        this.put(339, "Residència sacerdotal");
        this.put(340, "Residència seminaristes");
        this.put(341, "Residència senyorial");
        this.put(342, "Residencial");
        this.put(343, "Restaurant");
        this.put(344, "Retaule");
        this.put(345, "Revestiment o decoració d'edif");
        this.put(346, "Ruïna");
        this.put(347, "Ruïna consolidada");
        this.put(348, "Sèquia");
        this.put(349, "Safareig");
        this.put(350, "Sagristia");
        this.put(351, "Sala capitular");
        this.put(352, "Sala d'exposicions");
        this.put(353, "Sala de cups");
        this.put(354, "Sala de festes-discoteca");
        this.put(355, "Sanatori");
        this.put(356, "Sanatori mental");
        this.put(357, "Santuari");
        this.put(358, "Sarcòfag");
        this.put(359, "Segona residència");
        this.put(360, "Seminari");
        this.put(361, "Sepulcre");
        this.put(362, "Serveis administració");
        this.put(363, "Serveis sanitat");
        this.put(364, "Serveis socials");
        this.put(365, "Seu social");
        this.put(366, "Sindicat agrícola");
        this.put(367, "Sufragània");
        this.put(368, "Taller");
        this.put(369, "Taula");
        this.put(370, "Teatre");
        this.put(371, "Telèfons");
        this.put(372, "Telers");
        this.put(373, "Tomba");
        this.put(374, "Torre d'aigua");
        this.put(375, "Torre de defensa");
        this.put(376, "Torre de guaita");
        this.put(377, "Torre defensa aïllada");
        this.put(378, "Torre defensa de fortificació");
        this.put(379, "Torre defensa part d'edifici");
        this.put(380, "Tovallola");
        this.put(381, "Transports");
        this.put(382, "Trona");
        this.put(383, "Turístic");
        this.put(384, "Universitat");
        this.put(385, "Urna funerària");
        this.put(386, "Utensilis de cuina");
        this.put(387, "Vall");
        this.put(388, "Vestits");
        this.put(389, "Videoteca");
        this.put(390, "Vil·la romana");
        this.put(391, "Vitrall");
        this.put(392, "Xemeneia");
        this.put(397, "Farmàcia");
        this.put(399, "Consultori");
        this.put(402, "Clínica veterinària");
        this.put(404, "Beneficència");
        this.put(409, "Agrícola Ramadera");
        this.put(410, "Era");
        this.put(411, "llibreria");
        this.put(414, "Escut");
        this.put(415, "Imposta");
        this.put(416, "Ferramenta");
        this.put(417, "Baptisteri");
        this.put(418, "Creu ");
        this.put(419, "Timpà");
        this.put(420, "Cooperativa");
        this.put(421, "Culte-agrícola");
        this.put(422, "Baptisteri");
        this.put(423, "Funerària");
        this.put(424, "Necròpolis");
        this.put(425, "Tanca");
        this.put(426, "Aqüeducte");
        this.put(427, "Temple");
        this.put(428, "Termes");
        this.put(429, "Casa gremial");
        this.put(430, "Agrícola-Habitatge");
        this.put(432, "Llotja");
        this.put(433, "Torre telegrafia");
        this.put(434, "Tàpia");
        this.put(435, "Turisme rural");
        this.put(436, "Mines");
        this.put(437, "Serreria");
        this.put(438, "Rosari");
        this.put(439, "S");
        this.put(440, "Sinagoga");
        this.put(441, "pedró");
        this.put(442, "Viacrucis");
        this.put(443, "Agropecuària");
        this.put(444, "Búnquer");
        this.put(445, "Salina");
        this.put(446, "Dependència de la Inquisició");
        this.put(447, "Parc de bombers");
    }
}
