//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.12 at 05:24:55 PM CET 
//


package org.Custom.Transformations.formats.gene.common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ClassificacioArqueologicType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ClassificacioArqueologicType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Incoat BCIN"/&gt;
 *     &lt;enumeration value="Declarat BCIN"/&gt;
 *     &lt;enumeration value="BCIL"/&gt;
 *     &lt;enumeration value="Declarat EPA"/&gt;
 *     &lt;enumeration value="Plans d'ordenació"/&gt;
 *     &lt;enumeration value="Altres"/&gt;
 *     &lt;enumeration value="Patrimoni Mundial"/&gt;
 *     &lt;enumeration value="Pendent comprovació"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ClassificacioArqueologicType")
@XmlEnum
public enum ClassificacioArqueologicType {

    @XmlEnumValue("Incoat BCIN")
    INCOAT_BCIN("Incoat BCIN"),
    @XmlEnumValue("Declarat BCIN")
    DECLARAT_BCIN("Declarat BCIN"),
    BCIL("BCIL"),
    @XmlEnumValue("Declarat EPA")
    DECLARAT_EPA("Declarat EPA"),
    @XmlEnumValue("Plans d'ordenaci\u00f3")
    PLANS_D_ORDENACIÓ("Plans d'ordenaci\u00f3"),
    @XmlEnumValue("Altres")
    ALTRES("Altres"),
    @XmlEnumValue("Patrimoni Mundial")
    PATRIMONI_MUNDIAL("Patrimoni Mundial"),
    @XmlEnumValue("Pendent comprovaci\u00f3")
    PENDENT_COMPROVACIÓ("Pendent comprovaci\u00f3");
    private final String value;

    ClassificacioArqueologicType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ClassificacioArqueologicType fromValue(String v) {
        for (ClassificacioArqueologicType c: ClassificacioArqueologicType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
