//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.12 at 05:24:55 PM CET 
//


package org.Custom.Transformations.formats.gene.common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ClassificacioArquitectonicType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ClassificacioArquitectonicType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Conjunt històric"/&gt;
 *     &lt;enumeration value="Entorn"/&gt;
 *     &lt;enumeration value="Jardí històric"/&gt;
 *     &lt;enumeration value="Lloc històric"/&gt;
 *     &lt;enumeration value="Monument històric"/&gt;
 *     &lt;enumeration value="Pendent"/&gt;
 *     &lt;enumeration value="Zona arqueològica"/&gt;
 *     &lt;enumeration value="Zona d'interès etnològic"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ClassificacioArquitectonicType")
@XmlEnum
public enum ClassificacioArquitectonicType {

    @XmlEnumValue("Conjunt hist\u00f2ric")
    CONJUNT_HISTÒRIC("Conjunt hist\u00f2ric"),
    @XmlEnumValue("Entorn")
    ENTORN("Entorn"),
    @XmlEnumValue("Jard\u00ed hist\u00f2ric")
    JARDÍ_HISTÒRIC("Jard\u00ed hist\u00f2ric"),
    @XmlEnumValue("Lloc hist\u00f2ric")
    LLOC_HISTÒRIC("Lloc hist\u00f2ric"),
    @XmlEnumValue("Monument hist\u00f2ric")
    MONUMENT_HISTÒRIC("Monument hist\u00f2ric"),
    @XmlEnumValue("Pendent")
    PENDENT("Pendent"),
    @XmlEnumValue("Zona arqueol\u00f2gica")
    ZONA_ARQUEOLÒGICA("Zona arqueol\u00f2gica"),
    @XmlEnumValue("Zona d'inter\u00e8s etnol\u00f2gic")
    ZONA_D_INTERÈS_ETNOLÒGIC("Zona d'inter\u00e8s etnol\u00f2gic");
    private final String value;

    ClassificacioArquitectonicType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ClassificacioArquitectonicType fromValue(String v) {
        for (ClassificacioArquitectonicType c: ClassificacioArquitectonicType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
