//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.12 at 05:24:55 PM CET 
//


package org.Custom.Transformations.formats.gene.common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComarcaType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ComarcaType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Alt Camp"/&gt;
 *     &lt;enumeration value="Alt Empordà"/&gt;
 *     &lt;enumeration value="Alt Penedès"/&gt;
 *     &lt;enumeration value="Alt Urgell"/&gt;
 *     &lt;enumeration value="Alta Ribagorça"/&gt;
 *     &lt;enumeration value="Anoia"/&gt;
 *     &lt;enumeration value="Bages"/&gt;
 *     &lt;enumeration value="Baix Camp"/&gt;
 *     &lt;enumeration value="Baix Ebre"/&gt;
 *     &lt;enumeration value="Baix Empordà"/&gt;
 *     &lt;enumeration value="Baix Llobregat"/&gt;
 *     &lt;enumeration value="Baix Penedès"/&gt;
 *     &lt;enumeration value="Barcelonès"/&gt;
 *     &lt;enumeration value="Berguedà"/&gt;
 *     &lt;enumeration value="Cerdanya"/&gt;
 *     &lt;enumeration value="Conca de Barberà"/&gt;
 *     &lt;enumeration value="Garraf"/&gt;
 *     &lt;enumeration value="Garrigues"/&gt;
 *     &lt;enumeration value="Garrotxa"/&gt;
 *     &lt;enumeration value="Gironès"/&gt;
 *     &lt;enumeration value="Maresme"/&gt;
 *     &lt;enumeration value="Montsià"/&gt;
 *     &lt;enumeration value="Noguera"/&gt;
 *     &lt;enumeration value="Osona"/&gt;
 *     &lt;enumeration value="Pallars Jussà"/&gt;
 *     &lt;enumeration value="Pallars Sobirà"/&gt;
 *     &lt;enumeration value="Pla d'Urgell"/&gt;
 *     &lt;enumeration value="Pla de l'Estany"/&gt;
 *     &lt;enumeration value="Priorat"/&gt;
 *     &lt;enumeration value="Ribera d'Ebre"/&gt;
 *     &lt;enumeration value="Ripollès"/&gt;
 *     &lt;enumeration value="Segarra"/&gt;
 *     &lt;enumeration value="Segrià"/&gt;
 *     &lt;enumeration value="Selva"/&gt;
 *     &lt;enumeration value="Solsonès"/&gt;
 *     &lt;enumeration value="Tarragonès"/&gt;
 *     &lt;enumeration value="Terra Alta"/&gt;
 *     &lt;enumeration value="Urgell"/&gt;
 *     &lt;enumeration value="Vallès Occidental"/&gt;
 *     &lt;enumeration value="Vallès Oriental"/&gt;
 *     &lt;enumeration value="Moianès"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ComarcaType")
@XmlEnum
public enum ComarcaType {

    @XmlEnumValue("Alt Camp")
    ALT_CAMP("Alt Camp"),
    @XmlEnumValue("Alt Empord\u00e0")
    ALT_EMPORDÀ("Alt Empord\u00e0"),
    @XmlEnumValue("Alt Pened\u00e8s")
    ALT_PENEDÈS("Alt Pened\u00e8s"),
    @XmlEnumValue("Alt Urgell")
    ALT_URGELL("Alt Urgell"),
    @XmlEnumValue("Alta Ribagor\u00e7a")
    ALTA_RIBAGORÇA("Alta Ribagor\u00e7a"),
    @XmlEnumValue("Anoia")
    ANOIA("Anoia"),
    @XmlEnumValue("Bages")
    BAGES("Bages"),
    @XmlEnumValue("Baix Camp")
    BAIX_CAMP("Baix Camp"),
    @XmlEnumValue("Baix Ebre")
    BAIX_EBRE("Baix Ebre"),
    @XmlEnumValue("Baix Empord\u00e0")
    BAIX_EMPORDÀ("Baix Empord\u00e0"),
    @XmlEnumValue("Baix Llobregat")
    BAIX_LLOBREGAT("Baix Llobregat"),
    @XmlEnumValue("Baix Pened\u00e8s")
    BAIX_PENEDÈS("Baix Pened\u00e8s"),
    @XmlEnumValue("Barcelon\u00e8s")
    BARCELONÈS("Barcelon\u00e8s"),
    @XmlEnumValue("Bergued\u00e0")
    BERGUEDÀ("Bergued\u00e0"),
    @XmlEnumValue("Cerdanya")
    CERDANYA("Cerdanya"),
    @XmlEnumValue("Conca de Barber\u00e0")
    CONCA_DE_BARBERÀ("Conca de Barber\u00e0"),
    @XmlEnumValue("Garraf")
    GARRAF("Garraf"),
    @XmlEnumValue("Garrigues")
    GARRIGUES("Garrigues"),
    @XmlEnumValue("Garrotxa")
    GARROTXA("Garrotxa"),
    @XmlEnumValue("Giron\u00e8s")
    GIRONÈS("Giron\u00e8s"),
    @XmlEnumValue("Maresme")
    MARESME("Maresme"),
    @XmlEnumValue("Montsi\u00e0")
    MONTSIÀ("Montsi\u00e0"),
    @XmlEnumValue("Noguera")
    NOGUERA("Noguera"),
    @XmlEnumValue("Osona")
    OSONA("Osona"),
    @XmlEnumValue("Pallars Juss\u00e0")
    PALLARS_JUSSÀ("Pallars Juss\u00e0"),
    @XmlEnumValue("Pallars Sobir\u00e0")
    PALLARS_SOBIRÀ("Pallars Sobir\u00e0"),
    @XmlEnumValue("Pla d'Urgell")
    PLA_D_URGELL("Pla d'Urgell"),
    @XmlEnumValue("Pla de l'Estany")
    PLA_DE_L_ESTANY("Pla de l'Estany"),
    @XmlEnumValue("Priorat")
    PRIORAT("Priorat"),
    @XmlEnumValue("Ribera d'Ebre")
    RIBERA_D_EBRE("Ribera d'Ebre"),
    @XmlEnumValue("Ripoll\u00e8s")
    RIPOLLÈS("Ripoll\u00e8s"),
    @XmlEnumValue("Segarra")
    SEGARRA("Segarra"),
    @XmlEnumValue("Segri\u00e0")
    SEGRIÀ("Segri\u00e0"),
    @XmlEnumValue("Selva")
    SELVA("Selva"),
    @XmlEnumValue("Solson\u00e8s")
    SOLSONÈS("Solson\u00e8s"),
    @XmlEnumValue("Tarragon\u00e8s")
    TARRAGONÈS("Tarragon\u00e8s"),
    @XmlEnumValue("Terra Alta")
    TERRA_ALTA("Terra Alta"),
    @XmlEnumValue("Urgell")
    URGELL("Urgell"),
    @XmlEnumValue("Vall\u00e8s Occidental")
    VALLÈS_OCCIDENTAL("Vall\u00e8s Occidental"),
    @XmlEnumValue("Vall\u00e8s Oriental")
    VALLÈS_ORIENTAL("Vall\u00e8s Oriental"),
    @XmlEnumValue("Moian\u00e8s")
    MOIANÈS("Moian\u00e8s");
    private final String value;

    ComarcaType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ComarcaType fromValue(String v) {
        for (ComarcaType c: ComarcaType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
