//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.12 at 05:24:55 PM CET 
//


package org.Custom.Transformations.formats.gene.common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CronologiaArqueologicType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CronologiaArqueologicType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Aragonià"/&gt;
 *     &lt;enumeration value="Bartonià"/&gt;
 *     &lt;enumeration value="Bronze ?"/&gt;
 *     &lt;enumeration value="Bronze"/&gt;
 *     &lt;enumeration value="Bronze Antic"/&gt;
 *     &lt;enumeration value="Bronze Final"/&gt;
 *     &lt;enumeration value="Bronze Final I"/&gt;
 *     &lt;enumeration value="Bronze Final II"/&gt;
 *     &lt;enumeration value="Bronze Final III"/&gt;
 *     &lt;enumeration value="Bronze Mig"/&gt;
 *     &lt;enumeration value="Calcolític ?"/&gt;
 *     &lt;enumeration value="Calcolític"/&gt;
 *     &lt;enumeration value="Cambrià"/&gt;
 *     &lt;enumeration value="Campanià"/&gt;
 *     &lt;enumeration value="Carbonífer"/&gt;
 *     &lt;enumeration value="Catià"/&gt;
 *     &lt;enumeration value="Cenomanià"/&gt;
 *     &lt;enumeration value="Cenozoic"/&gt;
 *     &lt;enumeration value="Coniacià"/&gt;
 *     &lt;enumeration value="Cretaci"/&gt;
 *     &lt;enumeration value="Cretaci inferior"/&gt;
 *     &lt;enumeration value="Cretaci superior"/&gt;
 *     &lt;enumeration value="Cuisià"/&gt;
 *     &lt;enumeration value="Desconeguda"/&gt;
 *     &lt;enumeration value="Devonià"/&gt;
 *     &lt;enumeration value="Dogger"/&gt;
 *     &lt;enumeration value="Eocè"/&gt;
 *     &lt;enumeration value="Eocè inferior"/&gt;
 *     &lt;enumeration value="Eocè mitjà"/&gt;
 *     &lt;enumeration value="Eocè superior"/&gt;
 *     &lt;enumeration value="Epipaleolític ?"/&gt;
 *     &lt;enumeration value="Epipaleolític"/&gt;
 *     &lt;enumeration value="Fenici"/&gt;
 *     &lt;enumeration value="Ferro-Ibèric ?"/&gt;
 *     &lt;enumeration value="Ferro-Ibèric"/&gt;
 *     &lt;enumeration value="Ferro-Ibèric Antic"/&gt;
 *     &lt;enumeration value="Ferro-Ibèric Final"/&gt;
 *     &lt;enumeration value="Ferro-Ibèric Ple"/&gt;
 *     &lt;enumeration value="Hel·lenístic"/&gt;
 *     &lt;enumeration value="Holocè"/&gt;
 *     &lt;enumeration value="Ilerdià"/&gt;
 *     &lt;enumeration value="Juràssic"/&gt;
 *     &lt;enumeration value="Leptolític (Indiferenciat) ?"/&gt;
 *     &lt;enumeration value="Leptolític (Indiferenciat)"/&gt;
 *     &lt;enumeration value="Lias"/&gt;
 *     &lt;enumeration value="Lutecià"/&gt;
 *     &lt;enumeration value="Maastrichtià"/&gt;
 *     &lt;enumeration value="Malm"/&gt;
 *     &lt;enumeration value="Medieval ?"/&gt;
 *     &lt;enumeration value="Medieval"/&gt;
 *     &lt;enumeration value="Medieval Baixa Edat Mitjana"/&gt;
 *     &lt;enumeration value="Medieval Catalunya vella sotmesa als Carolingis"/&gt;
 *     &lt;enumeration value="Medieval Comtes de Barcelona"/&gt;
 *     &lt;enumeration value="Medieval Consolidació Corona d'Aragó"/&gt;
 *     &lt;enumeration value="Medieval Domini visigòtic"/&gt;
 *     &lt;enumeration value="Medieval Món Islàmic"/&gt;
 *     &lt;enumeration value="Medieval Món Islàmic Califat"/&gt;
 *     &lt;enumeration value="Medieval Món Islàmic Emirat"/&gt;
 *     &lt;enumeration value="Medieval Món Islàmic Taifes"/&gt;
 *     &lt;enumeration value="Medieval Ocupació i domini musulmà"/&gt;
 *     &lt;enumeration value="Mesozoic"/&gt;
 *     &lt;enumeration value="Miocè"/&gt;
 *     &lt;enumeration value="Miocè inferior"/&gt;
 *     &lt;enumeration value="Miocè mitjà"/&gt;
 *     &lt;enumeration value="Miocè superior"/&gt;
 *     &lt;enumeration value="Modern ?"/&gt;
 *     &lt;enumeration value="Modern"/&gt;
 *     &lt;enumeration value="Neogen"/&gt;
 *     &lt;enumeration value="Neolític ?"/&gt;
 *     &lt;enumeration value="Neolític"/&gt;
 *     &lt;enumeration value="Neolític Antic"/&gt;
 *     &lt;enumeration value="Neolític Antic Cardial"/&gt;
 *     &lt;enumeration value="Neolític Antic Postcardial"/&gt;
 *     &lt;enumeration value="Neolític Final"/&gt;
 *     &lt;enumeration value="Neolític Mig-Recent"/&gt;
 *     &lt;enumeration value="Oligocè"/&gt;
 *     &lt;enumeration value="Oligocè inferior"/&gt;
 *     &lt;enumeration value="Oligocè superior"/&gt;
 *     &lt;enumeration value="Ordovicià"/&gt;
 *     &lt;enumeration value="Paleocè"/&gt;
 *     &lt;enumeration value="Paleocè inferior"/&gt;
 *     &lt;enumeration value="Paleocè superior"/&gt;
 *     &lt;enumeration value="Paleogen"/&gt;
 *     &lt;enumeration value="Paleolític ?"/&gt;
 *     &lt;enumeration value="Paleolític"/&gt;
 *     &lt;enumeration value="Paleolític Inferior"/&gt;
 *     &lt;enumeration value="Paleolític Inferior Arcaic"/&gt;
 *     &lt;enumeration value="Paleolític Inferior Arcaic amb peces més evolucionades"/&gt;
 *     &lt;enumeration value="Paleolític Inferior Mig-Indiferenciat"/&gt;
 *     &lt;enumeration value="Paleolític Mig"/&gt;
 *     &lt;enumeration value="Paleolític Superior"/&gt;
 *     &lt;enumeration value="Paleolític Sup. Final-Epipaleolític Antic (Indiferenciat) ?"/&gt;
 *     &lt;enumeration value="Paleolític Sup. Final-Epipaleolític Antic (Indiferenciat)"/&gt;
 *     &lt;enumeration value="Paleozoic"/&gt;
 *     &lt;enumeration value="Permià"/&gt;
 *     &lt;enumeration value="Pleistocè/Plistocè"/&gt;
 *     &lt;enumeration value="Pleistocè/Plistocè inferior"/&gt;
 *     &lt;enumeration value="Pleistocè/Plistocè mitjà"/&gt;
 *     &lt;enumeration value="Pleistocè/Plistocè superior"/&gt;
 *     &lt;enumeration value="Pliocè"/&gt;
 *     &lt;enumeration value="Pliocè inferior"/&gt;
 *     &lt;enumeration value="Pliocè superior"/&gt;
 *     &lt;enumeration value="Priabonià"/&gt;
 *     &lt;enumeration value="Quaternari"/&gt;
 *     &lt;enumeration value="Ramblià"/&gt;
 *     &lt;enumeration value="Romà ?"/&gt;
 *     &lt;enumeration value="Romà"/&gt;
 *     &lt;enumeration value="Romà Alt Imperi"/&gt;
 *     &lt;enumeration value="Romà August"/&gt;
 *     &lt;enumeration value="Romà Baix Imperi"/&gt;
 *     &lt;enumeration value="Romà República"/&gt;
 *     &lt;enumeration value="Romà Segle III"/&gt;
 *     &lt;enumeration value="Rupelià"/&gt;
 *     &lt;enumeration value="Ruscinià"/&gt;
 *     &lt;enumeration value="Santonià"/&gt;
 *     &lt;enumeration value="Segles XVIII-XX"/&gt;
 *     &lt;enumeration value="Senonià"/&gt;
 *     &lt;enumeration value="Silurià"/&gt;
 *     &lt;enumeration value="Terciari"/&gt;
 *     &lt;enumeration value="Triàsic"/&gt;
 *     &lt;enumeration value="Triàsic inferior"/&gt;
 *     &lt;enumeration value="Triàsic mitjà"/&gt;
 *     &lt;enumeration value="Triàsic superior"/&gt;
 *     &lt;enumeration value="Turolià"/&gt;
 *     &lt;enumeration value="Turonià"/&gt;
 *     &lt;enumeration value="Vallesià"/&gt;
 *     &lt;enumeration value="Vil·lanyià"/&gt;
 *     &lt;enumeration value="Ypresià"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "CronologiaArqueologicType")
@XmlEnum
public enum CronologiaArqueologicType {

    @XmlEnumValue("Aragoni\u00e0")
    VALUE_1("Aragoni\u00e0"),
    @XmlEnumValue("Bartoni\u00e0")
    VALUE_2("Bartoni\u00e0"),
    @XmlEnumValue("Bronze ?")
    VALUE_3("Bronze ?"),
    @XmlEnumValue("Bronze")
    VALUE_4("Bronze"),
    @XmlEnumValue("Bronze Antic")
    VALUE_5("Bronze Antic"),
    @XmlEnumValue("Bronze Final")
    VALUE_6("Bronze Final"),
    @XmlEnumValue("Bronze Final I")
    VALUE_7("Bronze Final I"),
    @XmlEnumValue("Bronze Final II")
    VALUE_8("Bronze Final II"),
    @XmlEnumValue("Bronze Final III")
    VALUE_9("Bronze Final III"),
    @XmlEnumValue("Bronze Mig")
    VALUE_10("Bronze Mig"),
    @XmlEnumValue("Calcol\u00edtic ?")
    VALUE_11("Calcol\u00edtic ?"),
    @XmlEnumValue("Calcol\u00edtic")
    VALUE_12("Calcol\u00edtic"),
    @XmlEnumValue("Cambri\u00e0")
    VALUE_13("Cambri\u00e0"),
    @XmlEnumValue("Campani\u00e0")
    VALUE_14("Campani\u00e0"),
    @XmlEnumValue("Carbon\u00edfer")
    VALUE_15("Carbon\u00edfer"),
    @XmlEnumValue("Cati\u00e0")
    VALUE_16("Cati\u00e0"),
    @XmlEnumValue("Cenomani\u00e0")
    VALUE_17("Cenomani\u00e0"),
    @XmlEnumValue("Cenozoic")
    VALUE_18("Cenozoic"),
    @XmlEnumValue("Coniaci\u00e0")
    VALUE_19("Coniaci\u00e0"),
    @XmlEnumValue("Cretaci")
    VALUE_20("Cretaci"),
    @XmlEnumValue("Cretaci inferior")
    VALUE_21("Cretaci inferior"),
    @XmlEnumValue("Cretaci superior")
    VALUE_22("Cretaci superior"),
    @XmlEnumValue("Cuisi\u00e0")
    VALUE_23("Cuisi\u00e0"),
    @XmlEnumValue("Desconeguda")
    VALUE_24("Desconeguda"),
    @XmlEnumValue("Devoni\u00e0")
    VALUE_25("Devoni\u00e0"),
    @XmlEnumValue("Dogger")
    VALUE_26("Dogger"),
    @XmlEnumValue("Eoc\u00e8")
    VALUE_27("Eoc\u00e8"),
    @XmlEnumValue("Eoc\u00e8 inferior")
    VALUE_28("Eoc\u00e8 inferior"),
    @XmlEnumValue("Eoc\u00e8 mitj\u00e0")
    VALUE_29("Eoc\u00e8 mitj\u00e0"),
    @XmlEnumValue("Eoc\u00e8 superior")
    VALUE_30("Eoc\u00e8 superior"),
    @XmlEnumValue("Epipaleol\u00edtic ?")
    VALUE_31("Epipaleol\u00edtic ?"),
    @XmlEnumValue("Epipaleol\u00edtic")
    VALUE_32("Epipaleol\u00edtic"),
    @XmlEnumValue("Fenici")
    VALUE_33("Fenici"),
    @XmlEnumValue("Ferro-Ib\u00e8ric ?")
    VALUE_34("Ferro-Ib\u00e8ric ?"),
    @XmlEnumValue("Ferro-Ib\u00e8ric")
    VALUE_35("Ferro-Ib\u00e8ric"),
    @XmlEnumValue("Ferro-Ib\u00e8ric Antic")
    VALUE_36("Ferro-Ib\u00e8ric Antic"),
    @XmlEnumValue("Ferro-Ib\u00e8ric Final")
    VALUE_37("Ferro-Ib\u00e8ric Final"),
    @XmlEnumValue("Ferro-Ib\u00e8ric Ple")
    VALUE_38("Ferro-Ib\u00e8ric Ple"),
    @XmlEnumValue("Hel\u00b7len\u00edstic")
    VALUE_39("Hel\u00b7len\u00edstic"),
    @XmlEnumValue("Holoc\u00e8")
    VALUE_40("Holoc\u00e8"),
    @XmlEnumValue("Ilerdi\u00e0")
    VALUE_41("Ilerdi\u00e0"),
    @XmlEnumValue("Jur\u00e0ssic")
    VALUE_42("Jur\u00e0ssic"),
    @XmlEnumValue("Leptol\u00edtic (Indiferenciat) ?")
    VALUE_43("Leptol\u00edtic (Indiferenciat) ?"),
    @XmlEnumValue("Leptol\u00edtic (Indiferenciat)")
    VALUE_44("Leptol\u00edtic (Indiferenciat)"),
    @XmlEnumValue("Lias")
    VALUE_45("Lias"),
    @XmlEnumValue("Luteci\u00e0")
    VALUE_46("Luteci\u00e0"),
    @XmlEnumValue("Maastrichti\u00e0")
    VALUE_47("Maastrichti\u00e0"),
    @XmlEnumValue("Malm")
    VALUE_48("Malm"),
    @XmlEnumValue("Medieval ?")
    VALUE_49("Medieval ?"),
    @XmlEnumValue("Medieval")
    VALUE_50("Medieval"),
    @XmlEnumValue("Medieval Baixa Edat Mitjana")
    VALUE_51("Medieval Baixa Edat Mitjana"),
    @XmlEnumValue("Medieval Catalunya vella sotmesa als Carolingis")
    VALUE_52("Medieval Catalunya vella sotmesa als Carolingis"),
    @XmlEnumValue("Medieval Comtes de Barcelona")
    VALUE_53("Medieval Comtes de Barcelona"),
    @XmlEnumValue("Medieval Consolidaci\u00f3 Corona d'Arag\u00f3")
    VALUE_54("Medieval Consolidaci\u00f3 Corona d'Arag\u00f3"),
    @XmlEnumValue("Medieval Domini visig\u00f2tic")
    VALUE_55("Medieval Domini visig\u00f2tic"),
    @XmlEnumValue("Medieval M\u00f3n Isl\u00e0mic")
    VALUE_56("Medieval M\u00f3n Isl\u00e0mic"),
    @XmlEnumValue("Medieval M\u00f3n Isl\u00e0mic Califat")
    VALUE_57("Medieval M\u00f3n Isl\u00e0mic Califat"),
    @XmlEnumValue("Medieval M\u00f3n Isl\u00e0mic Emirat")
    VALUE_58("Medieval M\u00f3n Isl\u00e0mic Emirat"),
    @XmlEnumValue("Medieval M\u00f3n Isl\u00e0mic Taifes")
    VALUE_59("Medieval M\u00f3n Isl\u00e0mic Taifes"),
    @XmlEnumValue("Medieval Ocupaci\u00f3 i domini musulm\u00e0")
    VALUE_60("Medieval Ocupaci\u00f3 i domini musulm\u00e0"),
    @XmlEnumValue("Mesozoic")
    VALUE_61("Mesozoic"),
    @XmlEnumValue("Mioc\u00e8")
    VALUE_62("Mioc\u00e8"),
    @XmlEnumValue("Mioc\u00e8 inferior")
    VALUE_63("Mioc\u00e8 inferior"),
    @XmlEnumValue("Mioc\u00e8 mitj\u00e0")
    VALUE_64("Mioc\u00e8 mitj\u00e0"),
    @XmlEnumValue("Mioc\u00e8 superior")
    VALUE_65("Mioc\u00e8 superior"),
    @XmlEnumValue("Modern ?")
    VALUE_66("Modern ?"),
    @XmlEnumValue("Modern")
    VALUE_67("Modern"),
    @XmlEnumValue("Neogen")
    VALUE_68("Neogen"),
    @XmlEnumValue("Neol\u00edtic ?")
    VALUE_69("Neol\u00edtic ?"),
    @XmlEnumValue("Neol\u00edtic")
    VALUE_70("Neol\u00edtic"),
    @XmlEnumValue("Neol\u00edtic Antic")
    VALUE_71("Neol\u00edtic Antic"),
    @XmlEnumValue("Neol\u00edtic Antic Cardial")
    VALUE_72("Neol\u00edtic Antic Cardial"),
    @XmlEnumValue("Neol\u00edtic Antic Postcardial")
    VALUE_73("Neol\u00edtic Antic Postcardial"),
    @XmlEnumValue("Neol\u00edtic Final")
    VALUE_74("Neol\u00edtic Final"),
    @XmlEnumValue("Neol\u00edtic Mig-Recent")
    VALUE_75("Neol\u00edtic Mig-Recent"),
    @XmlEnumValue("Oligoc\u00e8")
    VALUE_76("Oligoc\u00e8"),
    @XmlEnumValue("Oligoc\u00e8 inferior")
    VALUE_77("Oligoc\u00e8 inferior"),
    @XmlEnumValue("Oligoc\u00e8 superior")
    VALUE_78("Oligoc\u00e8 superior"),
    @XmlEnumValue("Ordovici\u00e0")
    VALUE_79("Ordovici\u00e0"),
    @XmlEnumValue("Paleoc\u00e8")
    VALUE_80("Paleoc\u00e8"),
    @XmlEnumValue("Paleoc\u00e8 inferior")
    VALUE_81("Paleoc\u00e8 inferior"),
    @XmlEnumValue("Paleoc\u00e8 superior")
    VALUE_82("Paleoc\u00e8 superior"),
    @XmlEnumValue("Paleogen")
    VALUE_83("Paleogen"),
    @XmlEnumValue("Paleol\u00edtic ?")
    VALUE_84("Paleol\u00edtic ?"),
    @XmlEnumValue("Paleol\u00edtic")
    VALUE_85("Paleol\u00edtic"),
    @XmlEnumValue("Paleol\u00edtic Inferior")
    VALUE_86("Paleol\u00edtic Inferior"),
    @XmlEnumValue("Paleol\u00edtic Inferior Arcaic")
    VALUE_87("Paleol\u00edtic Inferior Arcaic"),
    @XmlEnumValue("Paleol\u00edtic Inferior Arcaic amb peces m\u00e9s evolucionades")
    VALUE_88("Paleol\u00edtic Inferior Arcaic amb peces m\u00e9s evolucionades"),
    @XmlEnumValue("Paleol\u00edtic Inferior Mig-Indiferenciat")
    VALUE_89("Paleol\u00edtic Inferior Mig-Indiferenciat"),
    @XmlEnumValue("Paleol\u00edtic Mig")
    VALUE_90("Paleol\u00edtic Mig"),
    @XmlEnumValue("Paleol\u00edtic Superior")
    VALUE_91("Paleol\u00edtic Superior"),
    @XmlEnumValue("Paleol\u00edtic Sup. Final-Epipaleol\u00edtic Antic (Indiferenciat) ?")
    VALUE_92("Paleol\u00edtic Sup. Final-Epipaleol\u00edtic Antic (Indiferenciat) ?"),
    @XmlEnumValue("Paleol\u00edtic Sup. Final-Epipaleol\u00edtic Antic (Indiferenciat)")
    VALUE_93("Paleol\u00edtic Sup. Final-Epipaleol\u00edtic Antic (Indiferenciat)"),
    @XmlEnumValue("Paleozoic")
    VALUE_94("Paleozoic"),
    @XmlEnumValue("Permi\u00e0")
    VALUE_95("Permi\u00e0"),
    @XmlEnumValue("Pleistoc\u00e8/Plistoc\u00e8")
    VALUE_96("Pleistoc\u00e8/Plistoc\u00e8"),
    @XmlEnumValue("Pleistoc\u00e8/Plistoc\u00e8 inferior")
    VALUE_97("Pleistoc\u00e8/Plistoc\u00e8 inferior"),
    @XmlEnumValue("Pleistoc\u00e8/Plistoc\u00e8 mitj\u00e0")
    VALUE_98("Pleistoc\u00e8/Plistoc\u00e8 mitj\u00e0"),
    @XmlEnumValue("Pleistoc\u00e8/Plistoc\u00e8 superior")
    VALUE_99("Pleistoc\u00e8/Plistoc\u00e8 superior"),
    @XmlEnumValue("Plioc\u00e8")
    VALUE_100("Plioc\u00e8"),
    @XmlEnumValue("Plioc\u00e8 inferior")
    VALUE_101("Plioc\u00e8 inferior"),
    @XmlEnumValue("Plioc\u00e8 superior")
    VALUE_102("Plioc\u00e8 superior"),
    @XmlEnumValue("Priaboni\u00e0")
    VALUE_103("Priaboni\u00e0"),
    @XmlEnumValue("Quaternari")
    VALUE_104("Quaternari"),
    @XmlEnumValue("Rambli\u00e0")
    VALUE_105("Rambli\u00e0"),
    @XmlEnumValue("Rom\u00e0 ?")
    VALUE_106("Rom\u00e0 ?"),
    @XmlEnumValue("Rom\u00e0")
    VALUE_107("Rom\u00e0"),
    @XmlEnumValue("Rom\u00e0 Alt Imperi")
    VALUE_108("Rom\u00e0 Alt Imperi"),
    @XmlEnumValue("Rom\u00e0 August")
    VALUE_109("Rom\u00e0 August"),
    @XmlEnumValue("Rom\u00e0 Baix Imperi")
    VALUE_110("Rom\u00e0 Baix Imperi"),
    @XmlEnumValue("Rom\u00e0 Rep\u00fablica")
    VALUE_111("Rom\u00e0 Rep\u00fablica"),
    @XmlEnumValue("Rom\u00e0 Segle III")
    VALUE_112("Rom\u00e0 Segle III"),
    @XmlEnumValue("Rupeli\u00e0")
    VALUE_113("Rupeli\u00e0"),
    @XmlEnumValue("Ruscini\u00e0")
    VALUE_114("Ruscini\u00e0"),
    @XmlEnumValue("Santoni\u00e0")
    VALUE_115("Santoni\u00e0"),
    @XmlEnumValue("Segles XVIII-XX")
    VALUE_116("Segles XVIII-XX"),
    @XmlEnumValue("Senoni\u00e0")
    VALUE_117("Senoni\u00e0"),
    @XmlEnumValue("Siluri\u00e0")
    VALUE_118("Siluri\u00e0"),
    @XmlEnumValue("Terciari")
    VALUE_119("Terciari"),
    @XmlEnumValue("Tri\u00e0sic")
    VALUE_120("Tri\u00e0sic"),
    @XmlEnumValue("Tri\u00e0sic inferior")
    VALUE_121("Tri\u00e0sic inferior"),
    @XmlEnumValue("Tri\u00e0sic mitj\u00e0")
    VALUE_122("Tri\u00e0sic mitj\u00e0"),
    @XmlEnumValue("Tri\u00e0sic superior")
    VALUE_123("Tri\u00e0sic superior"),
    @XmlEnumValue("Turoli\u00e0")
    VALUE_124("Turoli\u00e0"),
    @XmlEnumValue("Turoni\u00e0")
    VALUE_125("Turoni\u00e0"),
    @XmlEnumValue("Vallesi\u00e0")
    VALUE_126("Vallesi\u00e0"),
    @XmlEnumValue("Vil\u00b7lanyi\u00e0")
    VALUE_127("Vil\u00b7lanyi\u00e0"),
    @XmlEnumValue("Ypresi\u00e0")
    VALUE_128("Ypresi\u00e0");
    private final String value;

    CronologiaArqueologicType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CronologiaArqueologicType fromValue(String v) {
        for (CronologiaArqueologicType c: CronologiaArqueologicType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
