//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.12 at 05:24:55 PM CET 
//


package org.Custom.Transformations.formats.gene.common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CronologiaArquitectonicType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CronologiaArquitectonicType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Ferro-Ibèric"/&gt;
 *     &lt;enumeration value="Grec"/&gt;
 *     &lt;enumeration value="Romà"/&gt;
 *     &lt;enumeration value="IV"/&gt;
 *     &lt;enumeration value="V"/&gt;
 *     &lt;enumeration value="Medieval"/&gt;
 *     &lt;enumeration value="VI"/&gt;
 *     &lt;enumeration value="VII"/&gt;
 *     &lt;enumeration value="VIII"/&gt;
 *     &lt;enumeration value="IX"/&gt;
 *     &lt;enumeration value="X"/&gt;
 *     &lt;enumeration value="XI"/&gt;
 *     &lt;enumeration value="XII"/&gt;
 *     &lt;enumeration value="XIII"/&gt;
 *     &lt;enumeration value="XIV"/&gt;
 *     &lt;enumeration value="XV"/&gt;
 *     &lt;enumeration value="XVI"/&gt;
 *     &lt;enumeration value="XVII"/&gt;
 *     &lt;enumeration value="XVIII"/&gt;
 *     &lt;enumeration value="XVIII Inici"/&gt;
 *     &lt;enumeration value="XVIII Mitjan"/&gt;
 *     &lt;enumeration value="XVIII Final"/&gt;
 *     &lt;enumeration value="XIX"/&gt;
 *     &lt;enumeration value="XIX Inici"/&gt;
 *     &lt;enumeration value="XIX Mitjan"/&gt;
 *     &lt;enumeration value="XIX Final"/&gt;
 *     &lt;enumeration value="XX"/&gt;
 *     &lt;enumeration value="XX Inici"/&gt;
 *     &lt;enumeration value="XX Mitjan"/&gt;
 *     &lt;enumeration value="XX Final"/&gt;
 *     &lt;enumeration value="XXI"/&gt;
 *     &lt;enumeration value="XXI Inici"/&gt;
 *     &lt;enumeration value="XXI Mitjan"/&gt;
 *     &lt;enumeration value="XXI Final"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "CronologiaArquitectonicType")
@XmlEnum
public enum CronologiaArquitectonicType {

    @XmlEnumValue("Ferro-Ib\u00e8ric")
    FERRO_IBÈRIC("Ferro-Ib\u00e8ric"),
    @XmlEnumValue("Grec")
    GREC("Grec"),
    @XmlEnumValue("Rom\u00e0")
    ROMÀ("Rom\u00e0"),
    IV("IV"),
    V("V"),
    @XmlEnumValue("Medieval")
    MEDIEVAL("Medieval"),
    VI("VI"),
    VII("VII"),
    VIII("VIII"),
    IX("IX"),
    X("X"),
    XI("XI"),
    XII("XII"),
    XIII("XIII"),
    XIV("XIV"),
    XV("XV"),
    XVI("XVI"),
    XVII("XVII"),
    XVIII("XVIII"),
    @XmlEnumValue("XVIII Inici")
    XVIII_INICI("XVIII Inici"),
    @XmlEnumValue("XVIII Mitjan")
    XVIII_MITJAN("XVIII Mitjan"),
    @XmlEnumValue("XVIII Final")
    XVIII_FINAL("XVIII Final"),
    XIX("XIX"),
    @XmlEnumValue("XIX Inici")
    XIX_INICI("XIX Inici"),
    @XmlEnumValue("XIX Mitjan")
    XIX_MITJAN("XIX Mitjan"),
    @XmlEnumValue("XIX Final")
    XIX_FINAL("XIX Final"),
    XX("XX"),
    @XmlEnumValue("XX Inici")
    XX_INICI("XX Inici"),
    @XmlEnumValue("XX Mitjan")
    XX_MITJAN("XX Mitjan"),
    @XmlEnumValue("XX Final")
    XX_FINAL("XX Final"),
    XXI("XXI"),
    @XmlEnumValue("XXI Inici")
    XXI_INICI("XXI Inici"),
    @XmlEnumValue("XXI Mitjan")
    XXI_MITJAN("XXI Mitjan"),
    @XmlEnumValue("XXI Final")
    XXI_FINAL("XXI Final");
    private final String value;

    CronologiaArquitectonicType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CronologiaArquitectonicType fromValue(String v) {
        for (CronologiaArquitectonicType c: CronologiaArquitectonicType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
