//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.12 at 05:24:55 PM CET 
//


package org.Custom.Transformations.formats.gene.common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EstilEpocaType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EstilEpocaType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Prehistòric"/&gt;
 *     &lt;enumeration value="Paleolític"/&gt;
 *     &lt;enumeration value="Neolític"/&gt;
 *     &lt;enumeration value="Edat dels Metalls"/&gt;
 *     &lt;enumeration value="Antic"/&gt;
 *     &lt;enumeration value="Ibèric"/&gt;
 *     &lt;enumeration value="Grec"/&gt;
 *     &lt;enumeration value="Romà"/&gt;
 *     &lt;enumeration value="Paleocristià"/&gt;
 *     &lt;enumeration value="Medieval"/&gt;
 *     &lt;enumeration value="Bizantí"/&gt;
 *     &lt;enumeration value="Visigot"/&gt;
 *     &lt;enumeration value="Islàmic"/&gt;
 *     &lt;enumeration value="Mossàrab"/&gt;
 *     &lt;enumeration value="Carolingi"/&gt;
 *     &lt;enumeration value="Pre-romànic"/&gt;
 *     &lt;enumeration value="Romànic"/&gt;
 *     &lt;enumeration value="Gòtic"/&gt;
 *     &lt;enumeration value="Modern"/&gt;
 *     &lt;enumeration value="Renaixement"/&gt;
 *     &lt;enumeration value="Manierisme"/&gt;
 *     &lt;enumeration value="Barroc"/&gt;
 *     &lt;enumeration value="Rococó"/&gt;
 *     &lt;enumeration value="Contemporani"/&gt;
 *     &lt;enumeration value="Neoclàssic"/&gt;
 *     &lt;enumeration value="Isabelí"/&gt;
 *     &lt;enumeration value="Alfonsí"/&gt;
 *     &lt;enumeration value="Romàntic"/&gt;
 *     &lt;enumeration value="Eclecticisme"/&gt;
 *     &lt;enumeration value="Realisme"/&gt;
 *     &lt;enumeration value="Impressionisme"/&gt;
 *     &lt;enumeration value="Modernisme"/&gt;
 *     &lt;enumeration value="Noucentisme"/&gt;
 *     &lt;enumeration value="Avantguardes"/&gt;
 *     &lt;enumeration value="Expressionisme"/&gt;
 *     &lt;enumeration value="Fauvisme"/&gt;
 *     &lt;enumeration value="Cubisme"/&gt;
 *     &lt;enumeration value="Dadaisme"/&gt;
 *     &lt;enumeration value="Constructivisme"/&gt;
 *     &lt;enumeration value="Surrealisme"/&gt;
 *     &lt;enumeration value="Art Decó"/&gt;
 *     &lt;enumeration value="Abstracció"/&gt;
 *     &lt;enumeration value="Expressionisme abstracte"/&gt;
 *     &lt;enumeration value="Naïf"/&gt;
 *     &lt;enumeration value="Informalisme"/&gt;
 *     &lt;enumeration value="Hiperrealisme"/&gt;
 *     &lt;enumeration value="Historicista"/&gt;
 *     &lt;enumeration value="Pop art"/&gt;
 *     &lt;enumeration value="Minimalisme"/&gt;
 *     &lt;enumeration value="Popular"/&gt;
 *     &lt;enumeration value="Racionalisme"/&gt;
 *     &lt;enumeration value="Precàmbrià"/&gt;
 *     &lt;enumeration value="Paleozoic"/&gt;
 *     &lt;enumeration value="Mesozoic"/&gt;
 *     &lt;enumeration value="Cenozoic"/&gt;
 *     &lt;enumeration value="Paleògen"/&gt;
 *     &lt;enumeration value="Neògen."/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "EstilEpocaType")
@XmlEnum
public enum EstilEpocaType {

    @XmlEnumValue("Prehist\u00f2ric")
    PREHISTÒRIC("Prehist\u00f2ric"),
    @XmlEnumValue("Paleol\u00edtic")
    PALEOLÍTIC("Paleol\u00edtic"),
    @XmlEnumValue("Neol\u00edtic")
    NEOLÍTIC("Neol\u00edtic"),
    @XmlEnumValue("Edat dels Metalls")
    EDAT_DELS_METALLS("Edat dels Metalls"),
    @XmlEnumValue("Antic")
    ANTIC("Antic"),
    @XmlEnumValue("Ib\u00e8ric")
    IBÈRIC("Ib\u00e8ric"),
    @XmlEnumValue("Grec")
    GREC("Grec"),
    @XmlEnumValue("Rom\u00e0")
    ROMÀ("Rom\u00e0"),
    @XmlEnumValue("Paleocristi\u00e0")
    PALEOCRISTIÀ("Paleocristi\u00e0"),
    @XmlEnumValue("Medieval")
    MEDIEVAL("Medieval"),
    @XmlEnumValue("Bizant\u00ed")
    BIZANTÍ("Bizant\u00ed"),
    @XmlEnumValue("Visigot")
    VISIGOT("Visigot"),
    @XmlEnumValue("Isl\u00e0mic")
    ISLÀMIC("Isl\u00e0mic"),
    @XmlEnumValue("Moss\u00e0rab")
    MOSSÀRAB("Moss\u00e0rab"),
    @XmlEnumValue("Carolingi")
    CAROLINGI("Carolingi"),
    @XmlEnumValue("Pre-rom\u00e0nic")
    PRE_ROMÀNIC("Pre-rom\u00e0nic"),
    @XmlEnumValue("Rom\u00e0nic")
    ROMÀNIC("Rom\u00e0nic"),
    @XmlEnumValue("G\u00f2tic")
    GÒTIC("G\u00f2tic"),
    @XmlEnumValue("Modern")
    MODERN("Modern"),
    @XmlEnumValue("Renaixement")
    RENAIXEMENT("Renaixement"),
    @XmlEnumValue("Manierisme")
    MANIERISME("Manierisme"),
    @XmlEnumValue("Barroc")
    BARROC("Barroc"),
    @XmlEnumValue("Rococ\u00f3")
    ROCOCÓ("Rococ\u00f3"),
    @XmlEnumValue("Contemporani")
    CONTEMPORANI("Contemporani"),
    @XmlEnumValue("Neocl\u00e0ssic")
    NEOCLÀSSIC("Neocl\u00e0ssic"),
    @XmlEnumValue("Isabel\u00ed")
    ISABELÍ("Isabel\u00ed"),
    @XmlEnumValue("Alfons\u00ed")
    ALFONSÍ("Alfons\u00ed"),
    @XmlEnumValue("Rom\u00e0ntic")
    ROMÀNTIC("Rom\u00e0ntic"),
    @XmlEnumValue("Eclecticisme")
    ECLECTICISME("Eclecticisme"),
    @XmlEnumValue("Realisme")
    REALISME("Realisme"),
    @XmlEnumValue("Impressionisme")
    IMPRESSIONISME("Impressionisme"),
    @XmlEnumValue("Modernisme")
    MODERNISME("Modernisme"),
    @XmlEnumValue("Noucentisme")
    NOUCENTISME("Noucentisme"),
    @XmlEnumValue("Avantguardes")
    AVANTGUARDES("Avantguardes"),
    @XmlEnumValue("Expressionisme")
    EXPRESSIONISME("Expressionisme"),
    @XmlEnumValue("Fauvisme")
    FAUVISME("Fauvisme"),
    @XmlEnumValue("Cubisme")
    CUBISME("Cubisme"),
    @XmlEnumValue("Dadaisme")
    DADAISME("Dadaisme"),
    @XmlEnumValue("Constructivisme")
    CONSTRUCTIVISME("Constructivisme"),
    @XmlEnumValue("Surrealisme")
    SURREALISME("Surrealisme"),
    @XmlEnumValue("Art Dec\u00f3")
    ART_DECÓ("Art Dec\u00f3"),
    @XmlEnumValue("Abstracci\u00f3")
    ABSTRACCIÓ("Abstracci\u00f3"),
    @XmlEnumValue("Expressionisme abstracte")
    EXPRESSIONISME_ABSTRACTE("Expressionisme abstracte"),
    @XmlEnumValue("Na\u00eff")
    NAÏF("Na\u00eff"),
    @XmlEnumValue("Informalisme")
    INFORMALISME("Informalisme"),
    @XmlEnumValue("Hiperrealisme")
    HIPERREALISME("Hiperrealisme"),
    @XmlEnumValue("Historicista")
    HISTORICISTA("Historicista"),
    @XmlEnumValue("Pop art")
    POP_ART("Pop art"),
    @XmlEnumValue("Minimalisme")
    MINIMALISME("Minimalisme"),
    @XmlEnumValue("Popular")
    POPULAR("Popular"),
    @XmlEnumValue("Racionalisme")
    RACIONALISME("Racionalisme"),
    @XmlEnumValue("Prec\u00e0mbri\u00e0")
    PRECÀMBRIÀ("Prec\u00e0mbri\u00e0"),
    @XmlEnumValue("Paleozoic")
    PALEOZOIC("Paleozoic"),
    @XmlEnumValue("Mesozoic")
    MESOZOIC("Mesozoic"),
    @XmlEnumValue("Cenozoic")
    CENOZOIC("Cenozoic"),
    @XmlEnumValue("Pale\u00f2gen")
    PALEÒGEN("Pale\u00f2gen"),
    @XmlEnumValue("Ne\u00f2gen.")
    NEÒGEN("Ne\u00f2gen.");
    private final String value;

    EstilEpocaType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EstilEpocaType fromValue(String v) {
        for (EstilEpocaType c: EstilEpocaType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
