//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.12 at 05:24:55 PM CET 
//


package org.Custom.Transformations.formats.gene.common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OriginalActualType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OriginalActualType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Administratiu"/&gt;
 *     &lt;enumeration value="Científic"/&gt;
 *     &lt;enumeration value="Cultural"/&gt;
 *     &lt;enumeration value="Estructural"/&gt;
 *     &lt;enumeration value="Lúdic"/&gt;
 *     &lt;enumeration value="Ornamental"/&gt;
 *     &lt;enumeration value="Productiu"/&gt;
 *     &lt;enumeration value="Religiós"/&gt;
 *     &lt;enumeration value="Residencial"/&gt;
 *     &lt;enumeration value="Sense ús"/&gt;
 *     &lt;enumeration value="Simbòlic"/&gt;
 *     &lt;enumeration value="Social"/&gt;
 *     &lt;enumeration value="Altres"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "OriginalActualType")
@XmlEnum
public enum OriginalActualType {

    @XmlEnumValue("Administratiu")
    ADMINISTRATIU("Administratiu"),
    @XmlEnumValue("Cient\u00edfic")
    CIENTÍFIC("Cient\u00edfic"),
    @XmlEnumValue("Cultural")
    CULTURAL("Cultural"),
    @XmlEnumValue("Estructural")
    ESTRUCTURAL("Estructural"),
    @XmlEnumValue("L\u00fadic")
    LÚDIC("L\u00fadic"),
    @XmlEnumValue("Ornamental")
    ORNAMENTAL("Ornamental"),
    @XmlEnumValue("Productiu")
    PRODUCTIU("Productiu"),
    @XmlEnumValue("Religi\u00f3s")
    RELIGIÓS("Religi\u00f3s"),
    @XmlEnumValue("Residencial")
    RESIDENCIAL("Residencial"),
    @XmlEnumValue("Sense \u00fas")
    SENSE_ÚS("Sense \u00fas"),
    @XmlEnumValue("Simb\u00f2lic")
    SIMBÒLIC("Simb\u00f2lic"),
    @XmlEnumValue("Social")
    SOCIAL("Social"),
    @XmlEnumValue("Altres")
    ALTRES("Altres");
    private final String value;

    OriginalActualType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OriginalActualType fromValue(String v) {
        for (OriginalActualType c: OriginalActualType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
