//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.13 at 04:16:55 PM CET 
//


package org.Custom.Transformations.formats.gene.common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PropietariArquitectonicType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PropietariArquitectonicType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Privada"/&gt;
 *     &lt;enumeration value="Pública"/&gt;
 *     &lt;enumeration value="Eclesiàstica"/&gt;
 *     &lt;enumeration value="Cooperativa"/&gt;
 *     &lt;enumeration value="Pendent"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "PropietariArquitectonicType")
@XmlEnum
public enum PropietariArquitectonicType {

    @XmlEnumValue("Privada")
    PRIVADA("Privada"),
    @XmlEnumValue("P\u00fablica")
    PÚBLICA("P\u00fablica"),
    @XmlEnumValue("Eclesi\u00e0stica")
    ECLESIÀSTICA("Eclesi\u00e0stica"),
    @XmlEnumValue("Cooperativa")
    COOPERATIVA("Cooperativa"),
    @XmlEnumValue("Pendent")
    PENDENT("Pendent");
    private final String value;

    PropietariArquitectonicType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PropietariArquitectonicType fromValue(String v) {
        for (PropietariArquitectonicType c: PropietariArquitectonicType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
