//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.13 at 04:16:55 PM CET 
//


package org.Custom.Transformations.formats.gene.common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PropietariArqueologicType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PropietariArqueologicType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Pública"/&gt;
 *     &lt;enumeration value="Pública Nacional"/&gt;
 *     &lt;enumeration value="Pública Diputació"/&gt;
 *     &lt;enumeration value="Pública Municipal"/&gt;
 *     &lt;enumeration value="Pública Consell Comarcal"/&gt;
 *     &lt;enumeration value="Pública Estatal"/&gt;
 *     &lt;enumeration value="Eclesiàstica"/&gt;
 *     &lt;enumeration value="Privada"/&gt;
 *     &lt;enumeration value="Privada Institució"/&gt;
 *     &lt;enumeration value="Privada Particular"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "PropietariArqueologicType")
@XmlEnum
public enum PropietariArqueologicType {

    @XmlEnumValue("P\u00fablica")
    PÚBLICA("P\u00fablica"),
    @XmlEnumValue("P\u00fablica Nacional")
    PÚBLICA_NACIONAL("P\u00fablica Nacional"),
    @XmlEnumValue("P\u00fablica Diputaci\u00f3")
    PÚBLICA_DIPUTACIÓ("P\u00fablica Diputaci\u00f3"),
    @XmlEnumValue("P\u00fablica Municipal")
    PÚBLICA_MUNICIPAL("P\u00fablica Municipal"),
    @XmlEnumValue("P\u00fablica Consell Comarcal")
    PÚBLICA_CONSELL_COMARCAL("P\u00fablica Consell Comarcal"),
    @XmlEnumValue("P\u00fablica Estatal")
    PÚBLICA_ESTATAL("P\u00fablica Estatal"),
    @XmlEnumValue("Eclesi\u00e0stica")
    ECLESIÀSTICA("Eclesi\u00e0stica"),
    @XmlEnumValue("Privada")
    PRIVADA("Privada"),
    @XmlEnumValue("Privada Instituci\u00f3")
    PRIVADA_INSTITUCIÓ("Privada Instituci\u00f3"),
    @XmlEnumValue("Privada Particular")
    PRIVADA_PARTICULAR("Privada Particular");
    private final String value;

    PropietariArqueologicType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PropietariArqueologicType fromValue(String v) {
        for (PropietariArqueologicType c: PropietariArqueologicType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
