//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.12 at 05:24:55 PM CET 
//


package org.Custom.Transformations.formats.gene.common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TipologiaArqueologicType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TipologiaArqueologicType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Prefitxa"/&gt;
 *     &lt;enumeration value="Jaciment arqueològic"/&gt;
 *     &lt;enumeration value="Resultat negatiu total"/&gt;
 *     &lt;enumeration value="Jaciment paleontològic"/&gt;
 *     &lt;enumeration value="Jaciment subaquàtic"/&gt;
 *     &lt;enumeration value="Element"/&gt;
 *     &lt;enumeration value="Pendent revisió"/&gt;
 *     &lt;enumeration value="Guerra Civil"/&gt;
 *     &lt;enumeration value="Resultat negatiu en superfície"/&gt;
 *     &lt;enumeration value="Resultat negatiu parcial"/&gt;
 *     &lt;enumeration value="Notícia històrica"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TipologiaArqueologicType")
@XmlEnum
public enum TipologiaArqueologicType {

    @XmlEnumValue("Prefitxa")
    PREFITXA("Prefitxa"),
    @XmlEnumValue("Jaciment arqueol\u00f2gic")
    JACIMENT_ARQUEOLÒGIC("Jaciment arqueol\u00f2gic"),
    @XmlEnumValue("Resultat negatiu total")
    RESULTAT_NEGATIU_TOTAL("Resultat negatiu total"),
    @XmlEnumValue("Jaciment paleontol\u00f2gic")
    JACIMENT_PALEONTOLÒGIC("Jaciment paleontol\u00f2gic"),
    @XmlEnumValue("Jaciment subaqu\u00e0tic")
    JACIMENT_SUBAQUÀTIC("Jaciment subaqu\u00e0tic"),
    @XmlEnumValue("Element")
    ELEMENT("Element"),
    @XmlEnumValue("Pendent revisi\u00f3")
    PENDENT_REVISIÓ("Pendent revisi\u00f3"),
    @XmlEnumValue("Guerra Civil")
    GUERRA_CIVIL("Guerra Civil"),
    @XmlEnumValue("Resultat negatiu en superf\u00edcie")
    RESULTAT_NEGATIU_EN_SUPERFÍCIE("Resultat negatiu en superf\u00edcie"),
    @XmlEnumValue("Resultat negatiu parcial")
    RESULTAT_NEGATIU_PARCIAL("Resultat negatiu parcial"),
    @XmlEnumValue("Not\u00edcia hist\u00f2rica")
    NOTÍCIA_HISTÒRICA("Not\u00edcia hist\u00f2rica");
    private final String value;

    TipologiaArqueologicType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TipologiaArqueologicType fromValue(String v) {
        for (TipologiaArqueologicType c: TipologiaArqueologicType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
