//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.12 at 05:24:55 PM CET 
//


package org.Custom.Transformations.formats.gene.common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TipologiaArquitectonicType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TipologiaArquitectonicType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Abadia"/&gt;
 *     &lt;enumeration value="Abandonat"/&gt;
 *     &lt;enumeration value="Abeurador"/&gt;
 *     &lt;enumeration value="Acadèmia"/&gt;
 *     &lt;enumeration value="Accessoris d'edificis"/&gt;
 *     &lt;enumeration value="Agrícola"/&gt;
 *     &lt;enumeration value="Agrícola-Ramadera-Habitatge"/&gt;
 *     &lt;enumeration value="Aixada"/&gt;
 *     &lt;enumeration value="Aixeta"/&gt;
 *     &lt;enumeration value="Aixopluc"/&gt;
 *     &lt;enumeration value="Ajuntament"/&gt;
 *     &lt;enumeration value="Alberg"/&gt;
 *     &lt;enumeration value="Altar"/&gt;
 *     &lt;enumeration value="Altres"/&gt;
 *     &lt;enumeration value="Altres fortificacions"/&gt;
 *     &lt;enumeration value="Altres usos"/&gt;
 *     &lt;enumeration value="Altres usos militars"/&gt;
 *     &lt;enumeration value="Ambulatori"/&gt;
 *     &lt;enumeration value="Antipendi"/&gt;
 *     &lt;enumeration value="Ara"/&gt;
 *     &lt;enumeration value="Arada"/&gt;
 *     &lt;enumeration value="Arrambador"/&gt;
 *     &lt;enumeration value="Arxiu"/&gt;
 *     &lt;enumeration value="Asil-llar de vells"/&gt;
 *     &lt;enumeration value="Associació de veïns"/&gt;
 *     &lt;enumeration value="Associacions"/&gt;
 *     &lt;enumeration value="Ateneu"/&gt;
 *     &lt;enumeration value="Auditori"/&gt;
 *     &lt;enumeration value="Balcó"/&gt;
 *     &lt;enumeration value="Balneari"/&gt;
 *     &lt;enumeration value="Banc"/&gt;
 *     &lt;enumeration value="Bar"/&gt;
 *     &lt;enumeration value="Barraca"/&gt;
 *     &lt;enumeration value="Barraca de caçador"/&gt;
 *     &lt;enumeration value="Biblioteca"/&gt;
 *     &lt;enumeration value="Biga"/&gt;
 *     &lt;enumeration value="Borda"/&gt;
 *     &lt;enumeration value="Botiga"/&gt;
 *     &lt;enumeration value="Bústia"/&gt;
 *     &lt;enumeration value="Cabana"/&gt;
 *     &lt;enumeration value="Cabana de pastor"/&gt;
 *     &lt;enumeration value="Cabana de vinya"/&gt;
 *     &lt;enumeration value="Cafeteria"/&gt;
 *     &lt;enumeration value="Calçat"/&gt;
 *     &lt;enumeration value="Calaixera"/&gt;
 *     &lt;enumeration value="Calvari"/&gt;
 *     &lt;enumeration value="Calze"/&gt;
 *     &lt;enumeration value="Camí"/&gt;
 *     &lt;enumeration value="Cambra agrària"/&gt;
 *     &lt;enumeration value="Camp aviació"/&gt;
 *     &lt;enumeration value="Campana"/&gt;
 *     &lt;enumeration value="Campanar"/&gt;
 *     &lt;enumeration value="Canal"/&gt;
 *     &lt;enumeration value="Canònica"/&gt;
 *     &lt;enumeration value="Cap de biga"/&gt;
 *     &lt;enumeration value="Capella"/&gt;
 *     &lt;enumeration value="Capella lateral"/&gt;
 *     &lt;enumeration value="Capella-Canònica"/&gt;
 *     &lt;enumeration value="Capella-Cartoixa"/&gt;
 *     &lt;enumeration value="Capella-Castell"/&gt;
 *     &lt;enumeration value="Capella-Cementiri"/&gt;
 *     &lt;enumeration value="Capella-Col.legi"/&gt;
 *     &lt;enumeration value="Capella-Convent"/&gt;
 *     &lt;enumeration value="Capella-Escola"/&gt;
 *     &lt;enumeration value="Capella-Hospital"/&gt;
 *     &lt;enumeration value="Capella-Institució"/&gt;
 *     &lt;enumeration value="Capella-Masia"/&gt;
 *     &lt;enumeration value="Capella-Monestir"/&gt;
 *     &lt;enumeration value="Capella-Palau"/&gt;
 *     &lt;enumeration value="Capgròs"/&gt;
 *     &lt;enumeration value="Capitell"/&gt;
 *     &lt;enumeration value="Carrer"/&gt;
 *     &lt;enumeration value="Cartoixa"/&gt;
 *     &lt;enumeration value="Casa de colònies"/&gt;
 *     &lt;enumeration value="Casa de cultura"/&gt;
 *     &lt;enumeration value="Casa forta"/&gt;
 *     &lt;enumeration value="Casa senyorial"/&gt;
 *     &lt;enumeration value="Casal"/&gt;
 *     &lt;enumeration value="Casal de joves"/&gt;
 *     &lt;enumeration value="Casal de vells"/&gt;
 *     &lt;enumeration value="Casal fortificat"/&gt;
 *     &lt;enumeration value="Caserna"/&gt;
 *     &lt;enumeration value="Casino"/&gt;
 *     &lt;enumeration value="Castell"/&gt;
 *     &lt;enumeration value="Catedral"/&gt;
 *     &lt;enumeration value="Cava"/&gt;
 *     &lt;enumeration value="Cel.la"/&gt;
 *     &lt;enumeration value="Celler"/&gt;
 *     &lt;enumeration value="Celler cooperatiu"/&gt;
 *     &lt;enumeration value="Cementiri"/&gt;
 *     &lt;enumeration value="Central elèctrica"/&gt;
 *     &lt;enumeration value="Central tèrmica"/&gt;
 *     &lt;enumeration value="Centre cultural"/&gt;
 *     &lt;enumeration value="Centre excursionista"/&gt;
 *     &lt;enumeration value="Centre recreatiu"/&gt;
 *     &lt;enumeration value="Ceràmica"/&gt;
 *     &lt;enumeration value="Cinema"/&gt;
 *     &lt;enumeration value="Cisterna"/&gt;
 *     &lt;enumeration value="Ciutadella"/&gt;
 *     &lt;enumeration value="Clínica"/&gt;
 *     &lt;enumeration value="Clau de volta"/&gt;
 *     &lt;enumeration value="Claustre"/&gt;
 *     &lt;enumeration value="Cleda"/&gt;
 *     &lt;enumeration value="Club"/&gt;
 *     &lt;enumeration value="Col·legi professional"/&gt;
 *     &lt;enumeration value="Colònia industrial"/&gt;
 *     &lt;enumeration value="Colomar"/&gt;
 *     &lt;enumeration value="Columna"/&gt;
 *     &lt;enumeration value="Comercial"/&gt;
 *     &lt;enumeration value="Complement"/&gt;
 *     &lt;enumeration value="Comunidor"/&gt;
 *     &lt;enumeration value="Conducció d'aigua"/&gt;
 *     &lt;enumeration value="Consell Comarcal"/&gt;
 *     &lt;enumeration value="Construcció efímera"/&gt;
 *     &lt;enumeration value="Convent"/&gt;
 *     &lt;enumeration value="Cooperativa agrícola"/&gt;
 *     &lt;enumeration value="Corral"/&gt;
 *     &lt;enumeration value="Correus"/&gt;
 *     &lt;enumeration value="Cort"/&gt;
 *     &lt;enumeration value="Cortinatges"/&gt;
 *     &lt;enumeration value="Cotxeres"/&gt;
 *     &lt;enumeration value="Creu de terme"/&gt;
 *     &lt;enumeration value="Creu processional"/&gt;
 *     &lt;enumeration value="Cuina"/&gt;
 *     &lt;enumeration value="Culte"/&gt;
 *     &lt;enumeration value="Culte-habitatge"/&gt;
 *     &lt;enumeration value="Cultura"/&gt;
 *     &lt;enumeration value="Cups"/&gt;
 *     &lt;enumeration value="Custòdia"/&gt;
 *     &lt;enumeration value="Defensiva"/&gt;
 *     &lt;enumeration value="Defensiva-culte"/&gt;
 *     &lt;enumeration value="Defensiva-habitatge"/&gt;
 *     &lt;enumeration value="Dependències diverses"/&gt;
 *     &lt;enumeration value="Desaparegut"/&gt;
 *     &lt;enumeration value="Diputació"/&gt;
 *     &lt;enumeration value="Dispensari"/&gt;
 *     &lt;enumeration value="Dormitori"/&gt;
 *     &lt;enumeration value="Drassanes"/&gt;
 *     &lt;enumeration value="Editorial"/&gt;
 *     &lt;enumeration value="Egrafiats"/&gt;
 *     &lt;enumeration value="Eines agrícoles"/&gt;
 *     &lt;enumeration value="Empedrat"/&gt;
 *     &lt;enumeration value="En desús"/&gt;
 *     &lt;enumeration value="Enrajolat"/&gt;
 *     &lt;enumeration value="Ensenyament"/&gt;
 *     &lt;enumeration value="Ensenyament-habitatge"/&gt;
 *     &lt;enumeration value="Enteixinat"/&gt;
 *     &lt;enumeration value="Entitat bancària"/&gt;
 *     &lt;enumeration value="Equipaments industrials"/&gt;
 *     &lt;enumeration value="Ermita"/&gt;
 *     &lt;enumeration value="Escala"/&gt;
 *     &lt;enumeration value="Escola"/&gt;
 *     &lt;enumeration value="Escola d'arts i oficis"/&gt;
 *     &lt;enumeration value="Escola d'estiu"/&gt;
 *     &lt;enumeration value="Escola de música"/&gt;
 *     &lt;enumeration value="Escola taller"/&gt;
 *     &lt;enumeration value="Escorxador"/&gt;
 *     &lt;enumeration value="Escultura"/&gt;
 *     &lt;enumeration value="Església"/&gt;
 *     &lt;enumeration value="Església fortificada"/&gt;
 *     &lt;enumeration value="Església-Canònica"/&gt;
 *     &lt;enumeration value="Església-Cartoixa"/&gt;
 *     &lt;enumeration value="Església-Castell"/&gt;
 *     &lt;enumeration value="Església-Cementiri"/&gt;
 *     &lt;enumeration value="Església-Col.legi"/&gt;
 *     &lt;enumeration value="Església-Convent"/&gt;
 *     &lt;enumeration value="Església-Escola"/&gt;
 *     &lt;enumeration value="Església-Hospital"/&gt;
 *     &lt;enumeration value="Església-Institució"/&gt;
 *     &lt;enumeration value="Església-Masia"/&gt;
 *     &lt;enumeration value="Església-Monestir"/&gt;
 *     &lt;enumeration value="Església-Palau"/&gt;
 *     &lt;enumeration value="Espais de comunicació"/&gt;
 *     &lt;enumeration value="Espais de lleure"/&gt;
 *     &lt;enumeration value="Espais de lleure-comunicació"/&gt;
 *     &lt;enumeration value="Esplai"/&gt;
 *     &lt;enumeration value="Estable"/&gt;
 *     &lt;enumeration value="Estació"/&gt;
 *     &lt;enumeration value="Estela funerària"/&gt;
 *     &lt;enumeration value="Estructura o construcció"/&gt;
 *     &lt;enumeration value="Fàbrica"/&gt;
 *     &lt;enumeration value="Fanal"/&gt;
 *     &lt;enumeration value="Far"/&gt;
 *     &lt;enumeration value="Farga"/&gt;
 *     &lt;enumeration value="Fassina"/&gt;
 *     &lt;enumeration value="Filmoteca"/&gt;
 *     &lt;enumeration value="Finestra"/&gt;
 *     &lt;enumeration value="Fonda"/&gt;
 *     &lt;enumeration value="Fonoteca"/&gt;
 *     &lt;enumeration value="Font"/&gt;
 *     &lt;enumeration value="Forn"/&gt;
 *     &lt;enumeration value="Forn de calç"/&gt;
 *     &lt;enumeration value="Forn de pa"/&gt;
 *     &lt;enumeration value="Forrellat"/&gt;
 *     &lt;enumeration value="Fort"/&gt;
 *     &lt;enumeration value="Fortí"/&gt;
 *     &lt;enumeration value="Fortalesa"/&gt;
 *     &lt;enumeration value="Frontal d'altar"/&gt;
 *     &lt;enumeration value="Gàrgola"/&gt;
 *     &lt;enumeration value="Galeria d'art"/&gt;
 *     &lt;enumeration value="Garatge"/&gt;
 *     &lt;enumeration value="Gegant"/&gt;
 *     &lt;enumeration value="Generalitat"/&gt;
 *     &lt;enumeration value="Glorieta"/&gt;
 *     &lt;enumeration value="Govern civil"/&gt;
 *     &lt;enumeration value="Govern militar"/&gt;
 *     &lt;enumeration value="Graner"/&gt;
 *     &lt;enumeration value="Granja"/&gt;
 *     &lt;enumeration value="Gravat"/&gt;
 *     &lt;enumeration value="Guarderia"/&gt;
 *     &lt;enumeration value="Habitatge"/&gt;
 *     &lt;enumeration value="Habitatge d'obrers"/&gt;
 *     &lt;enumeration value="Habitatge de canonges"/&gt;
 *     &lt;enumeration value="Habitatge de monjos"/&gt;
 *     &lt;enumeration value="Habitatge plurifamiliar"/&gt;
 *     &lt;enumeration value="Habitatge temporer"/&gt;
 *     &lt;enumeration value="Habitatge unifamiliar"/&gt;
 *     &lt;enumeration value="Hemeroteca"/&gt;
 *     &lt;enumeration value="Hospici"/&gt;
 *     &lt;enumeration value="Hospital"/&gt;
 *     &lt;enumeration value="Hostal"/&gt;
 *     &lt;enumeration value="Hotel"/&gt;
 *     &lt;enumeration value="Imatge"/&gt;
 *     &lt;enumeration value="Indumentària"/&gt;
 *     &lt;enumeration value="Industrial"/&gt;
 *     &lt;enumeration value="Industrial-habitatge"/&gt;
 *     &lt;enumeration value="Instal.lació esportiva"/&gt;
 *     &lt;enumeration value="Instal.lació minera"/&gt;
 *     &lt;enumeration value="Institut"/&gt;
 *     &lt;enumeration value="Instrument musical"/&gt;
 *     &lt;enumeration value="Interiors"/&gt;
 *     &lt;enumeration value="Internat"/&gt;
 *     &lt;enumeration value="Jardí"/&gt;
 *     &lt;enumeration value="Joia"/&gt;
 *     &lt;enumeration value="Jutjat"/&gt;
 *     &lt;enumeration value="Llençols"/&gt;
 *     &lt;enumeration value="Lleure"/&gt;
 *     &lt;enumeration value="Llinda"/&gt;
 *     &lt;enumeration value="Llindar"/&gt;
 *     &lt;enumeration value="Llit"/&gt;
 *     &lt;enumeration value="Llosa sepulcral"/&gt;
 *     &lt;enumeration value="Llum"/&gt;
 *     &lt;enumeration value="Mènsula"/&gt;
 *     &lt;enumeration value="Magatzem"/&gt;
 *     &lt;enumeration value="Maquinària diversa"/&gt;
 *     &lt;enumeration value="Mas"/&gt;
 *     &lt;enumeration value="Masia"/&gt;
 *     &lt;enumeration value="Masia fortificada"/&gt;
 *     &lt;enumeration value="Masoveria"/&gt;
 *     &lt;enumeration value="Maternitat"/&gt;
 *     &lt;enumeration value="Mecanismes"/&gt;
 *     &lt;enumeration value="Mercat"/&gt;
 *     &lt;enumeration value="Militar"/&gt;
 *     &lt;enumeration value="Mina d'aigua"/&gt;
 *     &lt;enumeration value="Mirador"/&gt;
 *     &lt;enumeration value="Mobiliari"/&gt;
 *     &lt;enumeration value="Mobiliari urbà"/&gt;
 *     &lt;enumeration value="Molí"/&gt;
 *     &lt;enumeration value="Molí d'aigua"/&gt;
 *     &lt;enumeration value="Molí d'oli"/&gt;
 *     &lt;enumeration value="Molí draper"/&gt;
 *     &lt;enumeration value="Molí fariner"/&gt;
 *     &lt;enumeration value="Molí paperer"/&gt;
 *     &lt;enumeration value="Monestir"/&gt;
 *     &lt;enumeration value="Monument"/&gt;
 *     &lt;enumeration value="Monument commemoratiu"/&gt;
 *     &lt;enumeration value="Monument funerari"/&gt;
 *     &lt;enumeration value="Mosaic"/&gt;
 *     &lt;enumeration value="Muralla"/&gt;
 *     &lt;enumeration value="Museu"/&gt;
 *     &lt;enumeration value="Objectes d'art"/&gt;
 *     &lt;enumeration value="Objectes d'art popular"/&gt;
 *     &lt;enumeration value="Objectes de culte"/&gt;
 *     &lt;enumeration value="Obrador artesà"/&gt;
 *     &lt;enumeration value="Oficina"/&gt;
 *     &lt;enumeration value="Oratori"/&gt;
 *     &lt;enumeration value="Orfebreria"/&gt;
 *     &lt;enumeration value="Orfeó"/&gt;
 *     &lt;enumeration value="Palau"/&gt;
 *     &lt;enumeration value="Palau de l'abat"/&gt;
 *     &lt;enumeration value="Palau episcopal"/&gt;
 *     &lt;enumeration value="Pallissa"/&gt;
 *     &lt;enumeration value="Panteó"/&gt;
 *     &lt;enumeration value="Pany"/&gt;
 *     &lt;enumeration value="Parament de la llar"/&gt;
 *     &lt;enumeration value="Parc"/&gt;
 *     &lt;enumeration value="Paret"/&gt;
 *     &lt;enumeration value="Parròquia"/&gt;
 *     &lt;enumeration value="Part d'estructura o d'edifici"/&gt;
 *     &lt;enumeration value="Parvulari"/&gt;
 *     &lt;enumeration value="Passeig"/&gt;
 *     &lt;enumeration value="Paviment"/&gt;
 *     &lt;enumeration value="Pendent"/&gt;
 *     &lt;enumeration value="Pensió"/&gt;
 *     &lt;enumeration value="Pesquera"/&gt;
 *     &lt;enumeration value="Pesqueres"/&gt;
 *     &lt;enumeration value="Pica baptismal"/&gt;
 *     &lt;enumeration value="Pica beneitera"/&gt;
 *     &lt;enumeration value="Pintura"/&gt;
 *     &lt;enumeration value="Pintura mural"/&gt;
 *     &lt;enumeration value="Plaça"/&gt;
 *     &lt;enumeration value="Plafó ceràmic"/&gt;
 *     &lt;enumeration value="Pont"/&gt;
 *     &lt;enumeration value="Port"/&gt;
 *     &lt;enumeration value="Porta"/&gt;
 *     &lt;enumeration value="Portada"/&gt;
 *     &lt;enumeration value="Portal"/&gt;
 *     &lt;enumeration value="Pou"/&gt;
 *     &lt;enumeration value="Pou de gel"/&gt;
 *     &lt;enumeration value="Pre-industrial"/&gt;
 *     &lt;enumeration value="Presó"/&gt;
 *     &lt;enumeration value="Quadra"/&gt;
 *     &lt;enumeration value="Quadre"/&gt;
 *     &lt;enumeration value="Quiosc"/&gt;
 *     &lt;enumeration value="Ramadera"/&gt;
 *     &lt;enumeration value="Rasclet"/&gt;
 *     &lt;enumeration value="Rectoria"/&gt;
 *     &lt;enumeration value="Refetor"/&gt;
 *     &lt;enumeration value="Reformatori"/&gt;
 *     &lt;enumeration value="Refugi"/&gt;
 *     &lt;enumeration value="Refugi de muntanya"/&gt;
 *     &lt;enumeration value="Reixa"/&gt;
 *     &lt;enumeration value="Reliquiari"/&gt;
 *     &lt;enumeration value="Relleu"/&gt;
 *     &lt;enumeration value="Rellotge"/&gt;
 *     &lt;enumeration value="Rellotge de sol"/&gt;
 *     &lt;enumeration value="Resclosa"/&gt;
 *     &lt;enumeration value="Residència"/&gt;
 *     &lt;enumeration value="Residència comtal"/&gt;
 *     &lt;enumeration value="Residència d'estudiants"/&gt;
 *     &lt;enumeration value="Residència episcopal"/&gt;
 *     &lt;enumeration value="Residència reial"/&gt;
 *     &lt;enumeration value="Residència sacerdotal"/&gt;
 *     &lt;enumeration value="Residència seminaristes"/&gt;
 *     &lt;enumeration value="Residència senyorial"/&gt;
 *     &lt;enumeration value="Residencial"/&gt;
 *     &lt;enumeration value="Restaurant"/&gt;
 *     &lt;enumeration value="Retaule"/&gt;
 *     &lt;enumeration value="Revestiment o decoració d'edif"/&gt;
 *     &lt;enumeration value="Ruïna"/&gt;
 *     &lt;enumeration value="Ruïna consolidada"/&gt;
 *     &lt;enumeration value="Sèquia"/&gt;
 *     &lt;enumeration value="Safareig"/&gt;
 *     &lt;enumeration value="Sagristia"/&gt;
 *     &lt;enumeration value="Sala capitular"/&gt;
 *     &lt;enumeration value="Sala d'exposicions"/&gt;
 *     &lt;enumeration value="Sala de cups"/&gt;
 *     &lt;enumeration value="Sala de festes-discoteca"/&gt;
 *     &lt;enumeration value="Sanatori"/&gt;
 *     &lt;enumeration value="Sanatori mental"/&gt;
 *     &lt;enumeration value="Santuari"/&gt;
 *     &lt;enumeration value="Sarcòfag"/&gt;
 *     &lt;enumeration value="Segona residència"/&gt;
 *     &lt;enumeration value="Seminari"/&gt;
 *     &lt;enumeration value="Sepulcre"/&gt;
 *     &lt;enumeration value="Serveis administració"/&gt;
 *     &lt;enumeration value="Serveis sanitat"/&gt;
 *     &lt;enumeration value="Serveis socials"/&gt;
 *     &lt;enumeration value="Seu social"/&gt;
 *     &lt;enumeration value="Sindicat agrícola"/&gt;
 *     &lt;enumeration value="Sufragània"/&gt;
 *     &lt;enumeration value="Taller"/&gt;
 *     &lt;enumeration value="Taula"/&gt;
 *     &lt;enumeration value="Teatre"/&gt;
 *     &lt;enumeration value="Telèfons"/&gt;
 *     &lt;enumeration value="Telers"/&gt;
 *     &lt;enumeration value="Tomba"/&gt;
 *     &lt;enumeration value="Torre d'aigua"/&gt;
 *     &lt;enumeration value="Torre de defensa"/&gt;
 *     &lt;enumeration value="Torre de guaita"/&gt;
 *     &lt;enumeration value="Torre defensa aïllada"/&gt;
 *     &lt;enumeration value="Torre defensa de fortificació"/&gt;
 *     &lt;enumeration value="Torre defensa part d'edifici"/&gt;
 *     &lt;enumeration value="Tovallola"/&gt;
 *     &lt;enumeration value="Transports"/&gt;
 *     &lt;enumeration value="Trona"/&gt;
 *     &lt;enumeration value="Turístic"/&gt;
 *     &lt;enumeration value="Universitat"/&gt;
 *     &lt;enumeration value="Urna funerària"/&gt;
 *     &lt;enumeration value="Utensilis de cuina"/&gt;
 *     &lt;enumeration value="Vall"/&gt;
 *     &lt;enumeration value="Vestits"/&gt;
 *     &lt;enumeration value="Videoteca"/&gt;
 *     &lt;enumeration value="Vil·la romana"/&gt;
 *     &lt;enumeration value="Vitrall"/&gt;
 *     &lt;enumeration value="Xemeneia"/&gt;
 *     &lt;enumeration value="Farmàcia"/&gt;
 *     &lt;enumeration value="Consultori"/&gt;
 *     &lt;enumeration value="Clínica veterinària"/&gt;
 *     &lt;enumeration value="Beneficència"/&gt;
 *     &lt;enumeration value="Agrícola Ramadera"/&gt;
 *     &lt;enumeration value="Era"/&gt;
 *     &lt;enumeration value="llibreria"/&gt;
 *     &lt;enumeration value="Escut"/&gt;
 *     &lt;enumeration value="Imposta"/&gt;
 *     &lt;enumeration value="Ferramenta"/&gt;
 *     &lt;enumeration value="Baptisteri"/&gt;
 *     &lt;enumeration value="Creu "/&gt;
 *     &lt;enumeration value="Timpà"/&gt;
 *     &lt;enumeration value="Cooperativa"/&gt;
 *     &lt;enumeration value="Culte-agrícola"/&gt;
 *     &lt;enumeration value="Baptisteri"/&gt;
 *     &lt;enumeration value="Funerària"/&gt;
 *     &lt;enumeration value="Necròpolis"/&gt;
 *     &lt;enumeration value="Tanca"/&gt;
 *     &lt;enumeration value="Aqüeducte"/&gt;
 *     &lt;enumeration value="Temple"/&gt;
 *     &lt;enumeration value="Termes"/&gt;
 *     &lt;enumeration value="Casa gremial"/&gt;
 *     &lt;enumeration value="Agrícola-Habitatge"/&gt;
 *     &lt;enumeration value="Llotja"/&gt;
 *     &lt;enumeration value="Torre telegrafia"/&gt;
 *     &lt;enumeration value="Tàpia"/&gt;
 *     &lt;enumeration value="Turisme rural"/&gt;
 *     &lt;enumeration value="Mines"/&gt;
 *     &lt;enumeration value="Serreria"/&gt;
 *     &lt;enumeration value="Rosari"/&gt;
 *     &lt;enumeration value="S"/&gt;
 *     &lt;enumeration value="Sinagoga"/&gt;
 *     &lt;enumeration value="pedró"/&gt;
 *     &lt;enumeration value="Viacrucis"/&gt;
 *     &lt;enumeration value="Agropecuària"/&gt;
 *     &lt;enumeration value="Búnquer"/&gt;
 *     &lt;enumeration value="Salina"/&gt;
 *     &lt;enumeration value="Dependència de la Inquisició"/&gt;
 *     &lt;enumeration value="Parc de bombers"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TipologiaArquitectonicType")
@XmlEnum
public enum TipologiaArquitectonicType {

    @XmlEnumValue("Abadia")
    ABADIA("Abadia"),
    @XmlEnumValue("Abandonat")
    ABANDONAT("Abandonat"),
    @XmlEnumValue("Abeurador")
    ABEURADOR("Abeurador"),
    @XmlEnumValue("Acad\u00e8mia")
    ACADÈMIA("Acad\u00e8mia"),
    @XmlEnumValue("Accessoris d'edificis")
    ACCESSORIS_D_EDIFICIS("Accessoris d'edificis"),
    @XmlEnumValue("Agr\u00edcola")
    AGRÍCOLA("Agr\u00edcola"),
    @XmlEnumValue("Agr\u00edcola-Ramadera-Habitatge")
    AGRÍCOLA_RAMADERA_HABITATGE("Agr\u00edcola-Ramadera-Habitatge"),
    @XmlEnumValue("Aixada")
    AIXADA("Aixada"),
    @XmlEnumValue("Aixeta")
    AIXETA("Aixeta"),
    @XmlEnumValue("Aixopluc")
    AIXOPLUC("Aixopluc"),
    @XmlEnumValue("Ajuntament")
    AJUNTAMENT("Ajuntament"),
    @XmlEnumValue("Alberg")
    ALBERG("Alberg"),
    @XmlEnumValue("Altar")
    ALTAR("Altar"),
    @XmlEnumValue("Altres")
    ALTRES("Altres"),
    @XmlEnumValue("Altres fortificacions")
    ALTRES_FORTIFICACIONS("Altres fortificacions"),
    @XmlEnumValue("Altres usos")
    ALTRES_USOS("Altres usos"),
    @XmlEnumValue("Altres usos militars")
    ALTRES_USOS_MILITARS("Altres usos militars"),
    @XmlEnumValue("Ambulatori")
    AMBULATORI("Ambulatori"),
    @XmlEnumValue("Antipendi")
    ANTIPENDI("Antipendi"),
    @XmlEnumValue("Ara")
    ARA("Ara"),
    @XmlEnumValue("Arada")
    ARADA("Arada"),
    @XmlEnumValue("Arrambador")
    ARRAMBADOR("Arrambador"),
    @XmlEnumValue("Arxiu")
    ARXIU("Arxiu"),
    @XmlEnumValue("Asil-llar de vells")
    ASIL_LLAR_DE_VELLS("Asil-llar de vells"),
    @XmlEnumValue("Associaci\u00f3 de ve\u00efns")
    ASSOCIACIÓ_DE_VEÏNS("Associaci\u00f3 de ve\u00efns"),
    @XmlEnumValue("Associacions")
    ASSOCIACIONS("Associacions"),
    @XmlEnumValue("Ateneu")
    ATENEU("Ateneu"),
    @XmlEnumValue("Auditori")
    AUDITORI("Auditori"),
    @XmlEnumValue("Balc\u00f3")
    BALCÓ("Balc\u00f3"),
    @XmlEnumValue("Balneari")
    BALNEARI("Balneari"),
    @XmlEnumValue("Banc")
    BANC("Banc"),
    @XmlEnumValue("Bar")
    BAR("Bar"),
    @XmlEnumValue("Barraca")
    BARRACA("Barraca"),
    @XmlEnumValue("Barraca de ca\u00e7ador")
    BARRACA_DE_CAÇADOR("Barraca de ca\u00e7ador"),
    @XmlEnumValue("Biblioteca")
    BIBLIOTECA("Biblioteca"),
    @XmlEnumValue("Biga")
    BIGA("Biga"),
    @XmlEnumValue("Borda")
    BORDA("Borda"),
    @XmlEnumValue("Botiga")
    BOTIGA("Botiga"),
    @XmlEnumValue("B\u00fastia")
    BÚSTIA("B\u00fastia"),
    @XmlEnumValue("Cabana")
    CABANA("Cabana"),
    @XmlEnumValue("Cabana de pastor")
    CABANA_DE_PASTOR("Cabana de pastor"),
    @XmlEnumValue("Cabana de vinya")
    CABANA_DE_VINYA("Cabana de vinya"),
    @XmlEnumValue("Cafeteria")
    CAFETERIA("Cafeteria"),
    @XmlEnumValue("Cal\u00e7at")
    CALÇAT("Cal\u00e7at"),
    @XmlEnumValue("Calaixera")
    CALAIXERA("Calaixera"),
    @XmlEnumValue("Calvari")
    CALVARI("Calvari"),
    @XmlEnumValue("Calze")
    CALZE("Calze"),
    @XmlEnumValue("Cam\u00ed")
    CAMÍ("Cam\u00ed"),
    @XmlEnumValue("Cambra agr\u00e0ria")
    CAMBRA_AGRÀRIA("Cambra agr\u00e0ria"),
    @XmlEnumValue("Camp aviaci\u00f3")
    CAMP_AVIACIÓ("Camp aviaci\u00f3"),
    @XmlEnumValue("Campana")
    CAMPANA("Campana"),
    @XmlEnumValue("Campanar")
    CAMPANAR("Campanar"),
    @XmlEnumValue("Canal")
    CANAL("Canal"),
    @XmlEnumValue("Can\u00f2nica")
    CANÒNICA("Can\u00f2nica"),
    @XmlEnumValue("Cap de biga")
    CAP_DE_BIGA("Cap de biga"),
    @XmlEnumValue("Capella")
    CAPELLA("Capella"),
    @XmlEnumValue("Capella lateral")
    CAPELLA_LATERAL("Capella lateral"),
    @XmlEnumValue("Capella-Can\u00f2nica")
    CAPELLA_CANÒNICA("Capella-Can\u00f2nica"),
    @XmlEnumValue("Capella-Cartoixa")
    CAPELLA_CARTOIXA("Capella-Cartoixa"),
    @XmlEnumValue("Capella-Castell")
    CAPELLA_CASTELL("Capella-Castell"),
    @XmlEnumValue("Capella-Cementiri")
    CAPELLA_CEMENTIRI("Capella-Cementiri"),
    @XmlEnumValue("Capella-Col.legi")
    CAPELLA_COL_LEGI("Capella-Col.legi"),
    @XmlEnumValue("Capella-Convent")
    CAPELLA_CONVENT("Capella-Convent"),
    @XmlEnumValue("Capella-Escola")
    CAPELLA_ESCOLA("Capella-Escola"),
    @XmlEnumValue("Capella-Hospital")
    CAPELLA_HOSPITAL("Capella-Hospital"),
    @XmlEnumValue("Capella-Instituci\u00f3")
    CAPELLA_INSTITUCIÓ("Capella-Instituci\u00f3"),
    @XmlEnumValue("Capella-Masia")
    CAPELLA_MASIA("Capella-Masia"),
    @XmlEnumValue("Capella-Monestir")
    CAPELLA_MONESTIR("Capella-Monestir"),
    @XmlEnumValue("Capella-Palau")
    CAPELLA_PALAU("Capella-Palau"),
    @XmlEnumValue("Capgr\u00f2s")
    CAPGRÒS("Capgr\u00f2s"),
    @XmlEnumValue("Capitell")
    CAPITELL("Capitell"),
    @XmlEnumValue("Carrer")
    CARRER("Carrer"),
    @XmlEnumValue("Cartoixa")
    CARTOIXA("Cartoixa"),
    @XmlEnumValue("Casa de col\u00f2nies")
    CASA_DE_COLÒNIES("Casa de col\u00f2nies"),
    @XmlEnumValue("Casa de cultura")
    CASA_DE_CULTURA("Casa de cultura"),
    @XmlEnumValue("Casa forta")
    CASA_FORTA("Casa forta"),
    @XmlEnumValue("Casa senyorial")
    CASA_SENYORIAL("Casa senyorial"),
    @XmlEnumValue("Casal")
    CASAL("Casal"),
    @XmlEnumValue("Casal de joves")
    CASAL_DE_JOVES("Casal de joves"),
    @XmlEnumValue("Casal de vells")
    CASAL_DE_VELLS("Casal de vells"),
    @XmlEnumValue("Casal fortificat")
    CASAL_FORTIFICAT("Casal fortificat"),
    @XmlEnumValue("Caserna")
    CASERNA("Caserna"),
    @XmlEnumValue("Casino")
    CASINO("Casino"),
    @XmlEnumValue("Castell")
    CASTELL("Castell"),
    @XmlEnumValue("Catedral")
    CATEDRAL("Catedral"),
    @XmlEnumValue("Cava")
    CAVA("Cava"),
    @XmlEnumValue("Cel.la")
    CEL_LA("Cel.la"),
    @XmlEnumValue("Celler")
    CELLER("Celler"),
    @XmlEnumValue("Celler cooperatiu")
    CELLER_COOPERATIU("Celler cooperatiu"),
    @XmlEnumValue("Cementiri")
    CEMENTIRI("Cementiri"),
    @XmlEnumValue("Central el\u00e8ctrica")
    CENTRAL_ELÈCTRICA("Central el\u00e8ctrica"),
    @XmlEnumValue("Central t\u00e8rmica")
    CENTRAL_TÈRMICA("Central t\u00e8rmica"),
    @XmlEnumValue("Centre cultural")
    CENTRE_CULTURAL("Centre cultural"),
    @XmlEnumValue("Centre excursionista")
    CENTRE_EXCURSIONISTA("Centre excursionista"),
    @XmlEnumValue("Centre recreatiu")
    CENTRE_RECREATIU("Centre recreatiu"),
    @XmlEnumValue("Cer\u00e0mica")
    CERÀMICA("Cer\u00e0mica"),
    @XmlEnumValue("Cinema")
    CINEMA("Cinema"),
    @XmlEnumValue("Cisterna")
    CISTERNA("Cisterna"),
    @XmlEnumValue("Ciutadella")
    CIUTADELLA("Ciutadella"),
    @XmlEnumValue("Cl\u00ednica")
    CLÍNICA("Cl\u00ednica"),
    @XmlEnumValue("Clau de volta")
    CLAU_DE_VOLTA("Clau de volta"),
    @XmlEnumValue("Claustre")
    CLAUSTRE("Claustre"),
    @XmlEnumValue("Cleda")
    CLEDA("Cleda"),
    @XmlEnumValue("Club")
    CLUB("Club"),
    @XmlEnumValue("Col\u00b7legi professional")
    COL_LEGI_PROFESSIONAL("Col\u00b7legi professional"),
    @XmlEnumValue("Col\u00f2nia industrial")
    COLÒNIA_INDUSTRIAL("Col\u00f2nia industrial"),
    @XmlEnumValue("Colomar")
    COLOMAR("Colomar"),
    @XmlEnumValue("Columna")
    COLUMNA("Columna"),
    @XmlEnumValue("Comercial")
    COMERCIAL("Comercial"),
    @XmlEnumValue("Complement")
    COMPLEMENT("Complement"),
    @XmlEnumValue("Comunidor")
    COMUNIDOR("Comunidor"),
    @XmlEnumValue("Conducci\u00f3 d'aigua")
    CONDUCCIÓ_D_AIGUA("Conducci\u00f3 d'aigua"),
    @XmlEnumValue("Consell Comarcal")
    CONSELL_COMARCAL("Consell Comarcal"),
    @XmlEnumValue("Construcci\u00f3 ef\u00edmera")
    CONSTRUCCIÓ_EFÍMERA("Construcci\u00f3 ef\u00edmera"),
    @XmlEnumValue("Convent")
    CONVENT("Convent"),
    @XmlEnumValue("Cooperativa agr\u00edcola")
    COOPERATIVA_AGRÍCOLA("Cooperativa agr\u00edcola"),
    @XmlEnumValue("Corral")
    CORRAL("Corral"),
    @XmlEnumValue("Correus")
    CORREUS("Correus"),
    @XmlEnumValue("Cort")
    CORT("Cort"),
    @XmlEnumValue("Cortinatges")
    CORTINATGES("Cortinatges"),
    @XmlEnumValue("Cotxeres")
    COTXERES("Cotxeres"),
    @XmlEnumValue("Creu de terme")
    CREU_DE_TERME("Creu de terme"),
    @XmlEnumValue("Creu processional")
    CREU_PROCESSIONAL("Creu processional"),
    @XmlEnumValue("Cuina")
    CUINA("Cuina"),
    @XmlEnumValue("Culte")
    CULTE("Culte"),
    @XmlEnumValue("Culte-habitatge")
    CULTE_HABITATGE("Culte-habitatge"),
    @XmlEnumValue("Cultura")
    CULTURA("Cultura"),
    @XmlEnumValue("Cups")
    CUPS("Cups"),
    @XmlEnumValue("Cust\u00f2dia")
    CUSTÒDIA("Cust\u00f2dia"),
    @XmlEnumValue("Defensiva")
    DEFENSIVA("Defensiva"),
    @XmlEnumValue("Defensiva-culte")
    DEFENSIVA_CULTE("Defensiva-culte"),
    @XmlEnumValue("Defensiva-habitatge")
    DEFENSIVA_HABITATGE("Defensiva-habitatge"),
    @XmlEnumValue("Depend\u00e8ncies diverses")
    DEPENDÈNCIES_DIVERSES("Depend\u00e8ncies diverses"),
    @XmlEnumValue("Desaparegut")
    DESAPAREGUT("Desaparegut"),
    @XmlEnumValue("Diputaci\u00f3")
    DIPUTACIÓ("Diputaci\u00f3"),
    @XmlEnumValue("Dispensari")
    DISPENSARI("Dispensari"),
    @XmlEnumValue("Dormitori")
    DORMITORI("Dormitori"),
    @XmlEnumValue("Drassanes")
    DRASSANES("Drassanes"),
    @XmlEnumValue("Editorial")
    EDITORIAL("Editorial"),
    @XmlEnumValue("Egrafiats")
    EGRAFIATS("Egrafiats"),
    @XmlEnumValue("Eines agr\u00edcoles")
    EINES_AGRÍCOLES("Eines agr\u00edcoles"),
    @XmlEnumValue("Empedrat")
    EMPEDRAT("Empedrat"),
    @XmlEnumValue("En des\u00fas")
    EN_DESÚS("En des\u00fas"),
    @XmlEnumValue("Enrajolat")
    ENRAJOLAT("Enrajolat"),
    @XmlEnumValue("Ensenyament")
    ENSENYAMENT("Ensenyament"),
    @XmlEnumValue("Ensenyament-habitatge")
    ENSENYAMENT_HABITATGE("Ensenyament-habitatge"),
    @XmlEnumValue("Enteixinat")
    ENTEIXINAT("Enteixinat"),
    @XmlEnumValue("Entitat banc\u00e0ria")
    ENTITAT_BANCÀRIA("Entitat banc\u00e0ria"),
    @XmlEnumValue("Equipaments industrials")
    EQUIPAMENTS_INDUSTRIALS("Equipaments industrials"),
    @XmlEnumValue("Ermita")
    ERMITA("Ermita"),
    @XmlEnumValue("Escala")
    ESCALA("Escala"),
    @XmlEnumValue("Escola")
    ESCOLA("Escola"),
    @XmlEnumValue("Escola d'arts i oficis")
    ESCOLA_D_ARTS_I_OFICIS("Escola d'arts i oficis"),
    @XmlEnumValue("Escola d'estiu")
    ESCOLA_D_ESTIU("Escola d'estiu"),
    @XmlEnumValue("Escola de m\u00fasica")
    ESCOLA_DE_MÚSICA("Escola de m\u00fasica"),
    @XmlEnumValue("Escola taller")
    ESCOLA_TALLER("Escola taller"),
    @XmlEnumValue("Escorxador")
    ESCORXADOR("Escorxador"),
    @XmlEnumValue("Escultura")
    ESCULTURA("Escultura"),
    @XmlEnumValue("Esgl\u00e9sia")
    ESGLÉSIA("Esgl\u00e9sia"),
    @XmlEnumValue("Esgl\u00e9sia fortificada")
    ESGLÉSIA_FORTIFICADA("Esgl\u00e9sia fortificada"),
    @XmlEnumValue("Esgl\u00e9sia-Can\u00f2nica")
    ESGLÉSIA_CANÒNICA("Esgl\u00e9sia-Can\u00f2nica"),
    @XmlEnumValue("Esgl\u00e9sia-Cartoixa")
    ESGLÉSIA_CARTOIXA("Esgl\u00e9sia-Cartoixa"),
    @XmlEnumValue("Esgl\u00e9sia-Castell")
    ESGLÉSIA_CASTELL("Esgl\u00e9sia-Castell"),
    @XmlEnumValue("Esgl\u00e9sia-Cementiri")
    ESGLÉSIA_CEMENTIRI("Esgl\u00e9sia-Cementiri"),
    @XmlEnumValue("Esgl\u00e9sia-Col.legi")
    ESGLÉSIA_COL_LEGI("Esgl\u00e9sia-Col.legi"),
    @XmlEnumValue("Esgl\u00e9sia-Convent")
    ESGLÉSIA_CONVENT("Esgl\u00e9sia-Convent"),
    @XmlEnumValue("Esgl\u00e9sia-Escola")
    ESGLÉSIA_ESCOLA("Esgl\u00e9sia-Escola"),
    @XmlEnumValue("Esgl\u00e9sia-Hospital")
    ESGLÉSIA_HOSPITAL("Esgl\u00e9sia-Hospital"),
    @XmlEnumValue("Esgl\u00e9sia-Instituci\u00f3")
    ESGLÉSIA_INSTITUCIÓ("Esgl\u00e9sia-Instituci\u00f3"),
    @XmlEnumValue("Esgl\u00e9sia-Masia")
    ESGLÉSIA_MASIA("Esgl\u00e9sia-Masia"),
    @XmlEnumValue("Esgl\u00e9sia-Monestir")
    ESGLÉSIA_MONESTIR("Esgl\u00e9sia-Monestir"),
    @XmlEnumValue("Esgl\u00e9sia-Palau")
    ESGLÉSIA_PALAU("Esgl\u00e9sia-Palau"),
    @XmlEnumValue("Espais de comunicaci\u00f3")
    ESPAIS_DE_COMUNICACIÓ("Espais de comunicaci\u00f3"),
    @XmlEnumValue("Espais de lleure")
    ESPAIS_DE_LLEURE("Espais de lleure"),
    @XmlEnumValue("Espais de lleure-comunicaci\u00f3")
    ESPAIS_DE_LLEURE_COMUNICACIÓ("Espais de lleure-comunicaci\u00f3"),
    @XmlEnumValue("Esplai")
    ESPLAI("Esplai"),
    @XmlEnumValue("Estable")
    ESTABLE("Estable"),
    @XmlEnumValue("Estaci\u00f3")
    ESTACIÓ("Estaci\u00f3"),
    @XmlEnumValue("Estela funer\u00e0ria")
    ESTELA_FUNERÀRIA("Estela funer\u00e0ria"),
    @XmlEnumValue("Estructura o construcci\u00f3")
    ESTRUCTURA_O_CONSTRUCCIÓ("Estructura o construcci\u00f3"),
    @XmlEnumValue("F\u00e0brica")
    FÀBRICA("F\u00e0brica"),
    @XmlEnumValue("Fanal")
    FANAL("Fanal"),
    @XmlEnumValue("Far")
    FAR("Far"),
    @XmlEnumValue("Farga")
    FARGA("Farga"),
    @XmlEnumValue("Fassina")
    FASSINA("Fassina"),
    @XmlEnumValue("Filmoteca")
    FILMOTECA("Filmoteca"),
    @XmlEnumValue("Finestra")
    FINESTRA("Finestra"),
    @XmlEnumValue("Fonda")
    FONDA("Fonda"),
    @XmlEnumValue("Fonoteca")
    FONOTECA("Fonoteca"),
    @XmlEnumValue("Font")
    FONT("Font"),
    @XmlEnumValue("Forn")
    FORN("Forn"),
    @XmlEnumValue("Forn de cal\u00e7")
    FORN_DE_CALÇ("Forn de cal\u00e7"),
    @XmlEnumValue("Forn de pa")
    FORN_DE_PA("Forn de pa"),
    @XmlEnumValue("Forrellat")
    FORRELLAT("Forrellat"),
    @XmlEnumValue("Fort")
    FORT("Fort"),
    @XmlEnumValue("Fort\u00ed")
    FORTÍ("Fort\u00ed"),
    @XmlEnumValue("Fortalesa")
    FORTALESA("Fortalesa"),
    @XmlEnumValue("Frontal d'altar")
    FRONTAL_D_ALTAR("Frontal d'altar"),
    @XmlEnumValue("G\u00e0rgola")
    GÀRGOLA("G\u00e0rgola"),
    @XmlEnumValue("Galeria d'art")
    GALERIA_D_ART("Galeria d'art"),
    @XmlEnumValue("Garatge")
    GARATGE("Garatge"),
    @XmlEnumValue("Gegant")
    GEGANT("Gegant"),
    @XmlEnumValue("Generalitat")
    GENERALITAT("Generalitat"),
    @XmlEnumValue("Glorieta")
    GLORIETA("Glorieta"),
    @XmlEnumValue("Govern civil")
    GOVERN_CIVIL("Govern civil"),
    @XmlEnumValue("Govern militar")
    GOVERN_MILITAR("Govern militar"),
    @XmlEnumValue("Graner")
    GRANER("Graner"),
    @XmlEnumValue("Granja")
    GRANJA("Granja"),
    @XmlEnumValue("Gravat")
    GRAVAT("Gravat"),
    @XmlEnumValue("Guarderia")
    GUARDERIA("Guarderia"),
    @XmlEnumValue("Habitatge")
    HABITATGE("Habitatge"),
    @XmlEnumValue("Habitatge d'obrers")
    HABITATGE_D_OBRERS("Habitatge d'obrers"),
    @XmlEnumValue("Habitatge de canonges")
    HABITATGE_DE_CANONGES("Habitatge de canonges"),
    @XmlEnumValue("Habitatge de monjos")
    HABITATGE_DE_MONJOS("Habitatge de monjos"),
    @XmlEnumValue("Habitatge plurifamiliar")
    HABITATGE_PLURIFAMILIAR("Habitatge plurifamiliar"),
    @XmlEnumValue("Habitatge temporer")
    HABITATGE_TEMPORER("Habitatge temporer"),
    @XmlEnumValue("Habitatge unifamiliar")
    HABITATGE_UNIFAMILIAR("Habitatge unifamiliar"),
    @XmlEnumValue("Hemeroteca")
    HEMEROTECA("Hemeroteca"),
    @XmlEnumValue("Hospici")
    HOSPICI("Hospici"),
    @XmlEnumValue("Hospital")
    HOSPITAL("Hospital"),
    @XmlEnumValue("Hostal")
    HOSTAL("Hostal"),
    @XmlEnumValue("Hotel")
    HOTEL("Hotel"),
    @XmlEnumValue("Imatge")
    IMATGE("Imatge"),
    @XmlEnumValue("Indument\u00e0ria")
    INDUMENTÀRIA("Indument\u00e0ria"),
    @XmlEnumValue("Industrial")
    INDUSTRIAL("Industrial"),
    @XmlEnumValue("Industrial-habitatge")
    INDUSTRIAL_HABITATGE("Industrial-habitatge"),
    @XmlEnumValue("Instal.laci\u00f3 esportiva")
    INSTAL_LACIÓ_ESPORTIVA("Instal.laci\u00f3 esportiva"),
    @XmlEnumValue("Instal.laci\u00f3 minera")
    INSTAL_LACIÓ_MINERA("Instal.laci\u00f3 minera"),
    @XmlEnumValue("Institut")
    INSTITUT("Institut"),
    @XmlEnumValue("Instrument musical")
    INSTRUMENT_MUSICAL("Instrument musical"),
    @XmlEnumValue("Interiors")
    INTERIORS("Interiors"),
    @XmlEnumValue("Internat")
    INTERNAT("Internat"),
    @XmlEnumValue("Jard\u00ed")
    JARDÍ("Jard\u00ed"),
    @XmlEnumValue("Joia")
    JOIA("Joia"),
    @XmlEnumValue("Jutjat")
    JUTJAT("Jutjat"),
    @XmlEnumValue("Llen\u00e7ols")
    LLENÇOLS("Llen\u00e7ols"),
    @XmlEnumValue("Lleure")
    LLEURE("Lleure"),
    @XmlEnumValue("Llinda")
    LLINDA("Llinda"),
    @XmlEnumValue("Llindar")
    LLINDAR("Llindar"),
    @XmlEnumValue("Llit")
    LLIT("Llit"),
    @XmlEnumValue("Llosa sepulcral")
    LLOSA_SEPULCRAL("Llosa sepulcral"),
    @XmlEnumValue("Llum")
    LLUM("Llum"),
    @XmlEnumValue("M\u00e8nsula")
    MÈNSULA("M\u00e8nsula"),
    @XmlEnumValue("Magatzem")
    MAGATZEM("Magatzem"),
    @XmlEnumValue("Maquin\u00e0ria diversa")
    MAQUINÀRIA_DIVERSA("Maquin\u00e0ria diversa"),
    @XmlEnumValue("Mas")
    MAS("Mas"),
    @XmlEnumValue("Masia")
    MASIA("Masia"),
    @XmlEnumValue("Masia fortificada")
    MASIA_FORTIFICADA("Masia fortificada"),
    @XmlEnumValue("Masoveria")
    MASOVERIA("Masoveria"),
    @XmlEnumValue("Maternitat")
    MATERNITAT("Maternitat"),
    @XmlEnumValue("Mecanismes")
    MECANISMES("Mecanismes"),
    @XmlEnumValue("Mercat")
    MERCAT("Mercat"),
    @XmlEnumValue("Militar")
    MILITAR("Militar"),
    @XmlEnumValue("Mina d'aigua")
    MINA_D_AIGUA("Mina d'aigua"),
    @XmlEnumValue("Mirador")
    MIRADOR("Mirador"),
    @XmlEnumValue("Mobiliari")
    MOBILIARI("Mobiliari"),
    @XmlEnumValue("Mobiliari urb\u00e0")
    MOBILIARI_URBÀ("Mobiliari urb\u00e0"),
    @XmlEnumValue("Mol\u00ed")
    MOLÍ("Mol\u00ed"),
    @XmlEnumValue("Mol\u00ed d'aigua")
    MOLÍ_D_AIGUA("Mol\u00ed d'aigua"),
    @XmlEnumValue("Mol\u00ed d'oli")
    MOLÍ_D_OLI("Mol\u00ed d'oli"),
    @XmlEnumValue("Mol\u00ed draper")
    MOLÍ_DRAPER("Mol\u00ed draper"),
    @XmlEnumValue("Mol\u00ed fariner")
    MOLÍ_FARINER("Mol\u00ed fariner"),
    @XmlEnumValue("Mol\u00ed paperer")
    MOLÍ_PAPERER("Mol\u00ed paperer"),
    @XmlEnumValue("Monestir")
    MONESTIR("Monestir"),
    @XmlEnumValue("Monument")
    MONUMENT("Monument"),
    @XmlEnumValue("Monument commemoratiu")
    MONUMENT_COMMEMORATIU("Monument commemoratiu"),
    @XmlEnumValue("Monument funerari")
    MONUMENT_FUNERARI("Monument funerari"),
    @XmlEnumValue("Mosaic")
    MOSAIC("Mosaic"),
    @XmlEnumValue("Muralla")
    MURALLA("Muralla"),
    @XmlEnumValue("Museu")
    MUSEU("Museu"),
    @XmlEnumValue("Objectes d'art")
    OBJECTES_D_ART("Objectes d'art"),
    @XmlEnumValue("Objectes d'art popular")
    OBJECTES_D_ART_POPULAR("Objectes d'art popular"),
    @XmlEnumValue("Objectes de culte")
    OBJECTES_DE_CULTE("Objectes de culte"),
    @XmlEnumValue("Obrador artes\u00e0")
    OBRADOR_ARTESÀ("Obrador artes\u00e0"),
    @XmlEnumValue("Oficina")
    OFICINA("Oficina"),
    @XmlEnumValue("Oratori")
    ORATORI("Oratori"),
    @XmlEnumValue("Orfebreria")
    ORFEBRERIA("Orfebreria"),
    @XmlEnumValue("Orfe\u00f3")
    ORFEÓ("Orfe\u00f3"),
    @XmlEnumValue("Palau")
    PALAU("Palau"),
    @XmlEnumValue("Palau de l'abat")
    PALAU_DE_L_ABAT("Palau de l'abat"),
    @XmlEnumValue("Palau episcopal")
    PALAU_EPISCOPAL("Palau episcopal"),
    @XmlEnumValue("Pallissa")
    PALLISSA("Pallissa"),
    @XmlEnumValue("Pante\u00f3")
    PANTEÓ("Pante\u00f3"),
    @XmlEnumValue("Pany")
    PANY("Pany"),
    @XmlEnumValue("Parament de la llar")
    PARAMENT_DE_LA_LLAR("Parament de la llar"),
    @XmlEnumValue("Parc")
    PARC("Parc"),
    @XmlEnumValue("Paret")
    PARET("Paret"),
    @XmlEnumValue("Parr\u00f2quia")
    PARRÒQUIA("Parr\u00f2quia"),
    @XmlEnumValue("Part d'estructura o d'edifici")
    PART_D_ESTRUCTURA_O_D_EDIFICI("Part d'estructura o d'edifici"),
    @XmlEnumValue("Parvulari")
    PARVULARI("Parvulari"),
    @XmlEnumValue("Passeig")
    PASSEIG("Passeig"),
    @XmlEnumValue("Paviment")
    PAVIMENT("Paviment"),
    @XmlEnumValue("Pendent")
    PENDENT("Pendent"),
    @XmlEnumValue("Pensi\u00f3")
    PENSIÓ("Pensi\u00f3"),
    @XmlEnumValue("Pesquera")
    PESQUERA("Pesquera"),
    @XmlEnumValue("Pesqueres")
    PESQUERES("Pesqueres"),
    @XmlEnumValue("Pica baptismal")
    PICA_BAPTISMAL("Pica baptismal"),
    @XmlEnumValue("Pica beneitera")
    PICA_BENEITERA("Pica beneitera"),
    @XmlEnumValue("Pintura")
    PINTURA("Pintura"),
    @XmlEnumValue("Pintura mural")
    PINTURA_MURAL("Pintura mural"),
    @XmlEnumValue("Pla\u00e7a")
    PLAÇA("Pla\u00e7a"),
    @XmlEnumValue("Plaf\u00f3 cer\u00e0mic")
    PLAFÓ_CERÀMIC("Plaf\u00f3 cer\u00e0mic"),
    @XmlEnumValue("Pont")
    PONT("Pont"),
    @XmlEnumValue("Port")
    PORT("Port"),
    @XmlEnumValue("Porta")
    PORTA("Porta"),
    @XmlEnumValue("Portada")
    PORTADA("Portada"),
    @XmlEnumValue("Portal")
    PORTAL("Portal"),
    @XmlEnumValue("Pou")
    POU("Pou"),
    @XmlEnumValue("Pou de gel")
    POU_DE_GEL("Pou de gel"),
    @XmlEnumValue("Pre-industrial")
    PRE_INDUSTRIAL("Pre-industrial"),
    @XmlEnumValue("Pres\u00f3")
    PRESÓ("Pres\u00f3"),
    @XmlEnumValue("Quadra")
    QUADRA("Quadra"),
    @XmlEnumValue("Quadre")
    QUADRE("Quadre"),
    @XmlEnumValue("Quiosc")
    QUIOSC("Quiosc"),
    @XmlEnumValue("Ramadera")
    RAMADERA("Ramadera"),
    @XmlEnumValue("Rasclet")
    RASCLET("Rasclet"),
    @XmlEnumValue("Rectoria")
    RECTORIA("Rectoria"),
    @XmlEnumValue("Refetor")
    REFETOR("Refetor"),
    @XmlEnumValue("Reformatori")
    REFORMATORI("Reformatori"),
    @XmlEnumValue("Refugi")
    REFUGI("Refugi"),
    @XmlEnumValue("Refugi de muntanya")
    REFUGI_DE_MUNTANYA("Refugi de muntanya"),
    @XmlEnumValue("Reixa")
    REIXA("Reixa"),
    @XmlEnumValue("Reliquiari")
    RELIQUIARI("Reliquiari"),
    @XmlEnumValue("Relleu")
    RELLEU("Relleu"),
    @XmlEnumValue("Rellotge")
    RELLOTGE("Rellotge"),
    @XmlEnumValue("Rellotge de sol")
    RELLOTGE_DE_SOL("Rellotge de sol"),
    @XmlEnumValue("Resclosa")
    RESCLOSA("Resclosa"),
    @XmlEnumValue("Resid\u00e8ncia")
    RESIDÈNCIA("Resid\u00e8ncia"),
    @XmlEnumValue("Resid\u00e8ncia comtal")
    RESIDÈNCIA_COMTAL("Resid\u00e8ncia comtal"),
    @XmlEnumValue("Resid\u00e8ncia d'estudiants")
    RESIDÈNCIA_D_ESTUDIANTS("Resid\u00e8ncia d'estudiants"),
    @XmlEnumValue("Resid\u00e8ncia episcopal")
    RESIDÈNCIA_EPISCOPAL("Resid\u00e8ncia episcopal"),
    @XmlEnumValue("Resid\u00e8ncia reial")
    RESIDÈNCIA_REIAL("Resid\u00e8ncia reial"),
    @XmlEnumValue("Resid\u00e8ncia sacerdotal")
    RESIDÈNCIA_SACERDOTAL("Resid\u00e8ncia sacerdotal"),
    @XmlEnumValue("Resid\u00e8ncia seminaristes")
    RESIDÈNCIA_SEMINARISTES("Resid\u00e8ncia seminaristes"),
    @XmlEnumValue("Resid\u00e8ncia senyorial")
    RESIDÈNCIA_SENYORIAL("Resid\u00e8ncia senyorial"),
    @XmlEnumValue("Residencial")
    RESIDENCIAL("Residencial"),
    @XmlEnumValue("Restaurant")
    RESTAURANT("Restaurant"),
    @XmlEnumValue("Retaule")
    RETAULE("Retaule"),
    @XmlEnumValue("Revestiment o decoraci\u00f3 d'edif")
    REVESTIMENT_O_DECORACIÓ_D_EDIF("Revestiment o decoraci\u00f3 d'edif"),
    @XmlEnumValue("Ru\u00efna")
    RUÏNA("Ru\u00efna"),
    @XmlEnumValue("Ru\u00efna consolidada")
    RUÏNA_CONSOLIDADA("Ru\u00efna consolidada"),
    @XmlEnumValue("S\u00e8quia")
    SÈQUIA("S\u00e8quia"),
    @XmlEnumValue("Safareig")
    SAFAREIG("Safareig"),
    @XmlEnumValue("Sagristia")
    SAGRISTIA("Sagristia"),
    @XmlEnumValue("Sala capitular")
    SALA_CAPITULAR("Sala capitular"),
    @XmlEnumValue("Sala d'exposicions")
    SALA_D_EXPOSICIONS("Sala d'exposicions"),
    @XmlEnumValue("Sala de cups")
    SALA_DE_CUPS("Sala de cups"),
    @XmlEnumValue("Sala de festes-discoteca")
    SALA_DE_FESTES_DISCOTECA("Sala de festes-discoteca"),
    @XmlEnumValue("Sanatori")
    SANATORI("Sanatori"),
    @XmlEnumValue("Sanatori mental")
    SANATORI_MENTAL("Sanatori mental"),
    @XmlEnumValue("Santuari")
    SANTUARI("Santuari"),
    @XmlEnumValue("Sarc\u00f2fag")
    SARCÒFAG("Sarc\u00f2fag"),
    @XmlEnumValue("Segona resid\u00e8ncia")
    SEGONA_RESIDÈNCIA("Segona resid\u00e8ncia"),
    @XmlEnumValue("Seminari")
    SEMINARI("Seminari"),
    @XmlEnumValue("Sepulcre")
    SEPULCRE("Sepulcre"),
    @XmlEnumValue("Serveis administraci\u00f3")
    SERVEIS_ADMINISTRACIÓ("Serveis administraci\u00f3"),
    @XmlEnumValue("Serveis sanitat")
    SERVEIS_SANITAT("Serveis sanitat"),
    @XmlEnumValue("Serveis socials")
    SERVEIS_SOCIALS("Serveis socials"),
    @XmlEnumValue("Seu social")
    SEU_SOCIAL("Seu social"),
    @XmlEnumValue("Sindicat agr\u00edcola")
    SINDICAT_AGRÍCOLA("Sindicat agr\u00edcola"),
    @XmlEnumValue("Sufrag\u00e0nia")
    SUFRAGÀNIA("Sufrag\u00e0nia"),
    @XmlEnumValue("Taller")
    TALLER("Taller"),
    @XmlEnumValue("Taula")
    TAULA("Taula"),
    @XmlEnumValue("Teatre")
    TEATRE("Teatre"),
    @XmlEnumValue("Tel\u00e8fons")
    TELÈFONS("Tel\u00e8fons"),
    @XmlEnumValue("Telers")
    TELERS("Telers"),
    @XmlEnumValue("Tomba")
    TOMBA("Tomba"),
    @XmlEnumValue("Torre d'aigua")
    TORRE_D_AIGUA("Torre d'aigua"),
    @XmlEnumValue("Torre de defensa")
    TORRE_DE_DEFENSA("Torre de defensa"),
    @XmlEnumValue("Torre de guaita")
    TORRE_DE_GUAITA("Torre de guaita"),
    @XmlEnumValue("Torre defensa a\u00efllada")
    TORRE_DEFENSA_AÏLLADA("Torre defensa a\u00efllada"),
    @XmlEnumValue("Torre defensa de fortificaci\u00f3")
    TORRE_DEFENSA_DE_FORTIFICACIÓ("Torre defensa de fortificaci\u00f3"),
    @XmlEnumValue("Torre defensa part d'edifici")
    TORRE_DEFENSA_PART_D_EDIFICI("Torre defensa part d'edifici"),
    @XmlEnumValue("Tovallola")
    TOVALLOLA("Tovallola"),
    @XmlEnumValue("Transports")
    TRANSPORTS("Transports"),
    @XmlEnumValue("Trona")
    TRONA("Trona"),
    @XmlEnumValue("Tur\u00edstic")
    TURÍSTIC("Tur\u00edstic"),
    @XmlEnumValue("Universitat")
    UNIVERSITAT("Universitat"),
    @XmlEnumValue("Urna funer\u00e0ria")
    URNA_FUNERÀRIA("Urna funer\u00e0ria"),
    @XmlEnumValue("Utensilis de cuina")
    UTENSILIS_DE_CUINA("Utensilis de cuina"),
    @XmlEnumValue("Vall")
    VALL("Vall"),
    @XmlEnumValue("Vestits")
    VESTITS("Vestits"),
    @XmlEnumValue("Videoteca")
    VIDEOTECA("Videoteca"),
    @XmlEnumValue("Vil\u00b7la romana")
    VIL_LA_ROMANA("Vil\u00b7la romana"),
    @XmlEnumValue("Vitrall")
    VITRALL("Vitrall"),
    @XmlEnumValue("Xemeneia")
    XEMENEIA("Xemeneia"),
    @XmlEnumValue("Farm\u00e0cia")
    FARMÀCIA("Farm\u00e0cia"),
    @XmlEnumValue("Consultori")
    CONSULTORI("Consultori"),
    @XmlEnumValue("Cl\u00ednica veterin\u00e0ria")
    CLÍNICA_VETERINÀRIA("Cl\u00ednica veterin\u00e0ria"),
    @XmlEnumValue("Benefic\u00e8ncia")
    BENEFICÈNCIA("Benefic\u00e8ncia"),
    @XmlEnumValue("Agr\u00edcola Ramadera")
    AGRÍCOLA_RAMADERA("Agr\u00edcola Ramadera"),
    @XmlEnumValue("Era")
    ERA("Era"),
    @XmlEnumValue("llibreria")
    LLIBRERIA("llibreria"),
    @XmlEnumValue("Escut")
    ESCUT("Escut"),
    @XmlEnumValue("Imposta")
    IMPOSTA("Imposta"),
    @XmlEnumValue("Ferramenta")
    FERRAMENTA("Ferramenta"),
    @XmlEnumValue("Baptisteri")
    BAPTISTERI("Baptisteri"),
    @XmlEnumValue("Creu ")
    CREU("Creu "),
    @XmlEnumValue("Timp\u00e0")
    TIMPÀ("Timp\u00e0"),
    @XmlEnumValue("Cooperativa")
    COOPERATIVA("Cooperativa"),
    @XmlEnumValue("Culte-agr\u00edcola")
    CULTE_AGRÍCOLA("Culte-agr\u00edcola"),
    @XmlEnumValue("Funer\u00e0ria")
    FUNERÀRIA("Funer\u00e0ria"),
    @XmlEnumValue("Necr\u00f2polis")
    NECRÒPOLIS("Necr\u00f2polis"),
    @XmlEnumValue("Tanca")
    TANCA("Tanca"),
    @XmlEnumValue("Aq\u00fceducte")
    AQÜEDUCTE("Aq\u00fceducte"),
    @XmlEnumValue("Temple")
    TEMPLE("Temple"),
    @XmlEnumValue("Termes")
    TERMES("Termes"),
    @XmlEnumValue("Casa gremial")
    CASA_GREMIAL("Casa gremial"),
    @XmlEnumValue("Agr\u00edcola-Habitatge")
    AGRÍCOLA_HABITATGE("Agr\u00edcola-Habitatge"),
    @XmlEnumValue("Llotja")
    LLOTJA("Llotja"),
    @XmlEnumValue("Torre telegrafia")
    TORRE_TELEGRAFIA("Torre telegrafia"),
    @XmlEnumValue("T\u00e0pia")
    TÀPIA("T\u00e0pia"),
    @XmlEnumValue("Turisme rural")
    TURISME_RURAL("Turisme rural"),
    @XmlEnumValue("Mines")
    MINES("Mines"),
    @XmlEnumValue("Serreria")
    SERRERIA("Serreria"),
    @XmlEnumValue("Rosari")
    ROSARI("Rosari"),
    S("S"),
    @XmlEnumValue("Sinagoga")
    SINAGOGA("Sinagoga"),
    @XmlEnumValue("pedr\u00f3")
    PEDRÓ("pedr\u00f3"),
    @XmlEnumValue("Viacrucis")
    VIACRUCIS("Viacrucis"),
    @XmlEnumValue("Agropecu\u00e0ria")
    AGROPECUÀRIA("Agropecu\u00e0ria"),
    @XmlEnumValue("B\u00fanquer")
    BÚNQUER("B\u00fanquer"),
    @XmlEnumValue("Salina")
    SALINA("Salina"),
    @XmlEnumValue("Depend\u00e8ncia de la Inquisici\u00f3")
    DEPENDÈNCIA_DE_LA_INQUISICIÓ("Depend\u00e8ncia de la Inquisici\u00f3"),
    @XmlEnumValue("Parc de bombers")
    PARC_DE_BOMBERS("Parc de bombers");
    private final String value;

    TipologiaArquitectonicType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TipologiaArquitectonicType fromValue(String v) {
        for (TipologiaArquitectonicType c: TipologiaArquitectonicType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
