//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.12 at 05:24:55 PM CET 
//


package org.Custom.Transformations.formats.gene.common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UtilitzacioType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="UtilitzacioType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Romà"/&gt;
 *     &lt;enumeration value="Paleocristià/Tardo-romà"/&gt;
 *     &lt;enumeration value="Preromànic"/&gt;
 *     &lt;enumeration value="Romànic"/&gt;
 *     &lt;enumeration value="Gòtic"/&gt;
 *     &lt;enumeration value="Gòtic tardà"/&gt;
 *     &lt;enumeration value="Gòtic-Renaixement"/&gt;
 *     &lt;enumeration value="Renaixement"/&gt;
 *     &lt;enumeration value="Barroc"/&gt;
 *     &lt;enumeration value="Rococó"/&gt;
 *     &lt;enumeration value="Academicisme"/&gt;
 *     &lt;enumeration value="Neoclassicisme"/&gt;
 *     &lt;enumeration value="Neoclassicisme-Romàntic"/&gt;
 *     &lt;enumeration value="Historicisme"/&gt;
 *     &lt;enumeration value="Arquitectura del ferro"/&gt;
 *     &lt;enumeration value="Eclecticisme"/&gt;
 *     &lt;enumeration value="Modernisme"/&gt;
 *     &lt;enumeration value="Noucentisme"/&gt;
 *     &lt;enumeration value="Art Déco"/&gt;
 *     &lt;enumeration value="Racionalisme"/&gt;
 *     &lt;enumeration value="Monumentalisme Academicista"/&gt;
 *     &lt;enumeration value="Darreres tendències"/&gt;
 *     &lt;enumeration value="Obra popular"/&gt;
 *     &lt;enumeration value="Moviment Modern"/&gt;
 *     &lt;enumeration value="Sense estil definit"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "UtilitzacioType")
@XmlEnum
public enum UtilitzacioType {

    @XmlEnumValue("Rom\u00e0")
    ROMÀ("Rom\u00e0"),
    @XmlEnumValue("Paleocristi\u00e0/Tardo-rom\u00e0")
    PALEOCRISTIÀ_TARDO_ROMÀ("Paleocristi\u00e0/Tardo-rom\u00e0"),
    @XmlEnumValue("Prerom\u00e0nic")
    PREROMÀNIC("Prerom\u00e0nic"),
    @XmlEnumValue("Rom\u00e0nic")
    ROMÀNIC("Rom\u00e0nic"),
    @XmlEnumValue("G\u00f2tic")
    GÒTIC("G\u00f2tic"),
    @XmlEnumValue("G\u00f2tic tard\u00e0")
    GÒTIC_TARDÀ("G\u00f2tic tard\u00e0"),
    @XmlEnumValue("G\u00f2tic-Renaixement")
    GÒTIC_RENAIXEMENT("G\u00f2tic-Renaixement"),
    @XmlEnumValue("Renaixement")
    RENAIXEMENT("Renaixement"),
    @XmlEnumValue("Barroc")
    BARROC("Barroc"),
    @XmlEnumValue("Rococ\u00f3")
    ROCOCÓ("Rococ\u00f3"),
    @XmlEnumValue("Academicisme")
    ACADEMICISME("Academicisme"),
    @XmlEnumValue("Neoclassicisme")
    NEOCLASSICISME("Neoclassicisme"),
    @XmlEnumValue("Neoclassicisme-Rom\u00e0ntic")
    NEOCLASSICISME_ROMÀNTIC("Neoclassicisme-Rom\u00e0ntic"),
    @XmlEnumValue("Historicisme")
    HISTORICISME("Historicisme"),
    @XmlEnumValue("Arquitectura del ferro")
    ARQUITECTURA_DEL_FERRO("Arquitectura del ferro"),
    @XmlEnumValue("Eclecticisme")
    ECLECTICISME("Eclecticisme"),
    @XmlEnumValue("Modernisme")
    MODERNISME("Modernisme"),
    @XmlEnumValue("Noucentisme")
    NOUCENTISME("Noucentisme"),
    @XmlEnumValue("Art D\u00e9co")
    ART_DÉCO("Art D\u00e9co"),
    @XmlEnumValue("Racionalisme")
    RACIONALISME("Racionalisme"),
    @XmlEnumValue("Monumentalisme Academicista")
    MONUMENTALISME_ACADEMICISTA("Monumentalisme Academicista"),
    @XmlEnumValue("Darreres tend\u00e8ncies")
    DARRERES_TENDÈNCIES("Darreres tend\u00e8ncies"),
    @XmlEnumValue("Obra popular")
    OBRA_POPULAR("Obra popular"),
    @XmlEnumValue("Moviment Modern")
    MOVIMENT_MODERN("Moviment Modern"),
    @XmlEnumValue("Sense estil definit")
    SENSE_ESTIL_DEFINIT("Sense estil definit");
    private final String value;

    UtilitzacioType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static UtilitzacioType fromValue(String v) {
        for (UtilitzacioType c: UtilitzacioType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
